force-app/main/default/objects/Case/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negocio</fullName>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretor</fullName>
            </value>
            <value>
                <fullName>Analista</fullName>
            </value>
            <value>
                <fullName>Gestor(a)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <label>Unidade de negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investimentos</fullName>
            </value>
            <value>
                <fullName>Operações estruturadas</fullName>
            </value>
            <value>
                <fullName>Produtos financeiros - Imóveis</fullName>
            </value>
            <value>
                <fullName>Produtos financeiros - Veículos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CodigoProtheusRepresentantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <label>Unidade de negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produtos financeiros</fullName>
            </value>
            <value>
                <fullName>Investimentos</fullName>
            </value>
            <value>
                <fullName>Prime Euro Securitizadora</fullName>
            </value>
            <value>
                <fullName>Operações estruturadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Representante.recordType-meta.xml
<RecordType>
    <fullName>Representante</fullName>
    <active>true</active>
    <description>Tipo de registro criado para receber diferentes filiais dos mesmos representantes.</description>
    <label>Representante</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; IdFilial__c, IdFilial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretor</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Gestor(a)</fullName>
            </value>
            <value>
                <fullName>Analista</fullName>
            </value>
            <value>
                <fullName>Analista SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <label>Unidade de negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operações estruturadas</fullName>
            </value>
            <value>
                <fullName>Investimentos</fullName>
            </value>
            <value>
                <fullName>Produtos financeiros</fullName>
            </value>
            <value>
                <fullName>Formalização</fullName>
            </value>
            <value>
                <fullName>Crédito</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RepresentanteFactory.cls
public with sharing class RepresentanteFactory {

    public Map<String, User> gerarObjetoUser(List<RepresentanteSchema.Representante> representantesRequest, String idPerfil, Map<String, Id> mapGerentes, map<String, Boolean> mapDocumentosUserAtivos){
        Map<String, User> mapDocumentoRepresentante = new Map<String, User>();

        for(RepresentanteSchema.Representante representante : representantesRequest){
            Boolean runningInASandbox = Boolean.valueOf([SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox);

            List<String> userNameSplit = representante.email.split('@');
            String nomeAlias = representante.nome.substring(0,5);
            String numeroDocumento = Bdrs.Format.clearNumberFormatting(representante.documento);
            String primeiroNome = representante.nome.contains(' ') ? representante.nome.substringBefore(' ') : null;
            String sobrenome = primeiroNome != null ? representante.nome.substringAfter(' ') : representante.nome;
            String sufixoAmbiente = runningInASandbox ? '@euro.hml' : '@euro.prd';
            String usuarioFormatado = userNameSplit[0] + sufixoAmbiente;

            User usuario = new User(
                Alias = nomeAlias,
                Documento__c = numeroDocumento,
                Email = representante.email,
                EmailEncodingKey = 'UTF-8',
                FirstName = primeiroNome,
                IdExterno__c = numeroDocumento,
                IsActive = mapDocumentosUserAtivos.get(numeroDocumento),
                LanguageLocaleKey = 'pt_BR',
                LastName = sobrenome,
                LocaleSidKey = 'pt_BR',
                ProfileId = idPerfil,
                TimeZoneSidKey = 'America/Sao_Paulo',
                UserName = usuarioFormatado
            );

            //Tratamento para informações atualmente preenchidas manualmente
            if(!String.isEmpty(representante.funcao))
                usuario.Funcao__c = representante.Funcao;

            if(!String.isEmpty(representante.gerenteResponsavel))
                usuario.ManagerId = mapGerentes.get(representante.gerenteResponsavel);

            if(!String.isEmpty(representante.unidadeNegocio))
                usuario.UnidadeNegocio__c = representante.unidadeNegocio;

            mapDocumentoRepresentante.put(usuario.IdExterno__c, usuario);
        }

        return mapDocumentoRepresentante;
    }

    public Map<String, CodigoProtheus__c> gerarCodigosProtheus(List<RepresentanteSchema.Representante> representantesRequest, Map<String, Id> mapFilial, Map<String, User> mapDocumentoRepresentante){
        Map<String, CodigoProtheus__c> mapChaveCodProtheus = new Map<String, CodigoProtheus__c>();

        for(RepresentanteSchema.Representante representante : representantesRequest){
            if(!String.isBlank(representante.codigoProtheus)){
                String numeroDocumento = Bdrs.Format.clearNumberFormatting(representante.documento);

                CodigoProtheus__c codigoProtheus = new CodigoProtheus__c(
                    Ativo__c = representante.status,
                    Codigo__c = representante.codigoProtheus,
                    Filial__c = mapFilial.get(String.ValueOf(representante.filial)),
                    IdExterno__c =  representante.filial + '|' + numeroDocumento,
                    RecordTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Representante').getRecordTypeId(),
                    Representante__c = mapDocumentoRepresentante.get(numeroDocumento).Id
                );
    
                mapChaveCodProtheus.put(codigoProtheus.IdExterno__c, codigoProtheus);
            }
        }

        return mapChaveCodProtheus;
    }

    public List<Case> criarCasosParaNovosRepresentantes(List<Id> representantesIds, Id recordTypeId, Id FilaId) {
        List<Case> casosParaInserir = new List<Case>();
        for (Id representanteId : representantesIds) {
            Case novoCaso = new Case(
                Representante__c = representanteId,
                Subject = 'Configuração de usuário',
                Description = 'Configuração de usuário',
                Status = 'Novo',
                Type = 'Cadastro',
                RecordTypeId = recordTypeId,
                OwnerId = FilaId
            );
            casosParaInserir.add(novoCaso);
        }
        return casosParaInserir;
    }

}