force-app/main/default/objects/Case/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CodigoProtheusRepresentantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <label>Código Filial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; IdFilial__c, IdFilial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RepresentanteRepository.cls
public with sharing class RepresentanteRepository {

    public List<Profile> buscarPerfilPeloNome(String nomePerfil){
        return[
            SELECT
                Id,
                Name
            FROM
                Profile
            WHERE
                Name =: nomePerfil
        ];
    }

    public List<User> buscarUsuarioPeloNome(Set<String> nomeUsuario){
        return[
            SELECT
                Id,
                Name
            FROM
                User
            WHERE
                Name IN: nomeUsuario
        ];
    }

    public List<Filial__c> buscarFilialPorCodigo(Set<String> docFilial) {
        return [
            SELECT 
                Id,
                CodigoFilial__c
            FROM 
                Filial__c 
            WHERE 
                CodigoFilial__c IN: docFilial
        ];
    }

    public Id buscarRecordType(String nomeDoRecordType) {
        RecordType Rt = [
            SELECT 
                Id 
            FROM 
                RecordType
            WHERE SObjectType = 'Case' AND DeveloperName = :nomeDoRecordType
            
        ];
        return Rt.Id;
    }


    public Id buscarFila(String nomeDaFila) {
        Group fila = [
            SELECT 
                Id,
                Name
            FROM 
                Group 
            WHERE Type = 'Queue' AND DeveloperName = :nomeDaFila
        ];
        return fila.Id;
    }

    public List<CodigoProtheus__c> buscarCodigosProtheusAtivos(Set<String> documentos, Id representanteRecTypeId) {
        return [
            SELECT 
                Id, 
                Ativo__c,
                Representante__r.Documento__c,
            	Codigo__c
            FROM 
                CodigoProtheus__c
            WHERE 
                Representante__r.Documento__c IN :documentos
            AND
                RecordTypeId = :representanteRecTypeId
            AND 
                Ativo__c = true
        ];     
    }

    /* public List<CodigoProtheus__c> buscarCodigosProtheusExistentes(Id representanteRecTypeId, Set<Id> setRepresentantesIds, Set<String> setIdsExternos){
        return[
            SELECT
                Id,
                Codigo__c
            FROM
                CodigoProtheus__c
            WHERE
                IdExterno__c NOT IN: setIdsExternos
            AND 
                Representante__c IN: setRepresentantesIds
            AND
                RecordTypeId =: representanteRecTypeId
        ];
    } */

}