force-app/main/default/objects/Case/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Suporte.recordType-meta.xml
<RecordType>
    <fullName>Suporte</fullName>
    <active>true</active>
    <businessProcess>Casos - Suporte</businessProcess>
    <description>Casos relacionados à problemas, dúvidas e solicitações referente ao Salesforce.</description>
    <label>Suporte</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CodigoProtheusRepresentantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Representante.recordType-meta.xml
<RecordType>
    <fullName>Representante</fullName>
    <active>true</active>
    <description>Tipo de registro criado para receber diferentes filiais dos mesmos representantes.</description>
    <label>Representante</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <label>Código Filial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; IdFilial__c, IdFilial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RepresentanteService.cls
global class RepresentanteService {

    /* Os comentários presentes nas classes Representante, RepresentanteRepository e RepresentanceService foram adicionados para 
        caso futuramente seja necessário inativar a relação entre representante e filial anteriores, mantendo apenas os recentes ativos.
        Para funcionamento, basta retirar os comentários das classes mencionadas. */

    private Representante representanteClass = new Representante();
    private RepresentanteFactory factory = new RepresentanteFactory();
    private RepresentanteRepository repository = new RepresentanteRepository();

    global void criarRepresentantes(RepresentanteSchema.RepresentantesRequest representanteRequest){
        List<CodigoProtheus__c> lstCodProtheusAnteriores = new List<CodigoProtheus__c>();
        List<Filial__c> filiais = new List<Filial__c>();
        List<Profile> perfis = new List<Profile>();
        List<User> usuarios = new List<User>();
        Map<String, CodigoProtheus__c> mapChaveCodProtheus = new Map<String, CodigoProtheus__c>();
        Map<String, Id> mapFiliais = new Map<String, Id>();
        Map<String, Id> mapGerentes = new Map<String, Id>();
        Map<String, User> mapDocumentoRepresentante = new Map<String, User>();
        Map<String, Boolean> mapDocumentosUserAtivos = new Map<String, Boolean>();
        Set<Id> setRepresentantesIds = new Set<Id>();
        Set<String> codFilial = new Set<String>();
        Set<String> documentos = new Set<String>();
        Set<String> setNomesGerentes = new Set<String>();
    
        List<RepresentanteSchema.Representante> representantes = representanteRequest.representantes;

        Id representanteRecTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Representante').getRecordTypeId();
       
        for(RepresentanteSchema.Representante forRepresentante : representantes){
            String numeroDocumento = Bdrs.Format.clearNumberFormatting(forRepresentante.documento);
            documentos.add(numeroDocumento);
            if(forRepresentante.filial != null)
                codFilial.add(forRepresentante.filial);
            
            if(forRepresentante.gerenteResponsavel != null)
                setNomesGerentes.add(forRepresentante.gerenteResponsavel);
        }
        
        List<CodigoProtheus__c> codigosProtheusAtivos = repository.buscarCodigosProtheusAtivos(documentos, representanteRecTypeId);

        for (RepresentanteSchema.Representante forRepresentante : representantes) {
            String numeroDocumento = Bdrs.Format.clearNumberFormatting(forRepresentante.documento);
            if (!forRepresentante.status) {
                for (CodigoProtheus__c codigosAtivo : codigosProtheusAtivos) {
                    if (codigosAtivo.Representante__r.Documento__c == numeroDocumento && codigosAtivo.Codigo__c != forRepresentante.codigoProtheus ) {
                        mapDocumentosUserAtivos.put(numeroDocumento, true);
                        break;
                    }
                }
                
                if (mapDocumentosUserAtivos.get(numeroDocumento) == null) 
                    mapDocumentosUserAtivos.put(numeroDocumento, false);

            } else 
                mapDocumentosUserAtivos.put(numeroDocumento, forRepresentante.status);
        }

        filiais = this.repository.buscarFilialPorCodigo(codFilial);

        if(codFilial.size() == 0 || codFilial.size() != filiais.size())
            throw new Representante.RepresentanteException('Filial não encontrada');

        usuarios = this.repository.buscarUsuarioPeloNome(setNomesGerentes);
        perfis = this.repository.buscarPerfilPeloNome('Grupo Euro 17');

        for(Filial__c filial : filiais)
            mapFiliais.put(filial.CodigoFilial__c, filial.Id);

        for(User gerente : usuarios)
            mapGerentes.put(gerente.Name, gerente.Id);
    
        mapDocumentoRepresentante = this.factory.gerarObjetoUser(representanteRequest.representantes, perfis[0].Id, mapGerentes, mapDocumentosUserAtivos);
        
        List<Id> novosRepresentantesIds = this.representanteClass.criarRepresentante(mapDocumentoRepresentante);

        mapChaveCodProtheus = this.factory.gerarCodigosProtheus(representanteRequest.representantes, mapFiliais, mapDocumentoRepresentante);
        Representante.criarCodigoProtheus(JSON.serialize(mapChaveCodProtheus));

        /* for(CodigoProtheus__c codigoProtheus : mapChaveCodProtheus.values())
            setRepresentantesIds.add(codigoProtheus.Representante__c);

        Id representanteRecTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Representante').getRecordTypeId();
        lstCodProtheusAnteriores = this.repository.buscarCodigosProtheusExistentes(representanteRecTypeId, setRepresentantesIds, mapChaveCodProtheus.keySet());

        for(CodigoProtheus__c codigoProtheus : lstCodProtheusAnteriores)
            codigoProtheus.Ativo__c = false;

        Representante.inativarCodigosAnteriores(JSON.serialize(lstCodProtheusAnteriores)); */


        if (!novosRepresentantesIds.isEmpty()) {
            Id caseRecordTypeId = repository.buscarRecordType('Suporte');
            Id filaId = repository.buscarFila('Cadastramento');
            List<Case> casosParaInserir = factory.criarCasosParaNovosRepresentantes(novosRepresentantesIds, caseRecordTypeId, FilaId);
            String casosJson = JSON.serialize(casosParaInserir);
            Representante.inserirCasos(casosJson); 
        }
    }

}