force-app/main/default/objects/Beneficiario__c/Beneficiario__c.object-meta.xml
<CustomObject>
    <label>Beneficiário</label>
    <nameField>
        <label>Nome de Beneficiário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiario__c/fields/TelefoneInternacional__c.field-meta.xml
<CustomField>
    <fullName>TelefoneInternacional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo de controle para evitar validações e máscaras de números nacionais para números de telefone internacionais informados.</description>
    <label>Telefone internacional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BeneficiarioTriggerHandler.cls
public with sharing class BeneficiarioTriggerHandler extends Bdrs.TriggerHandler {
    
    private List<Beneficiario__c> lstBeneficiariosTelefoneFormat;

    public BeneficiarioTriggerHandler(){
        this.lstBeneficiariosTelefoneFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'TelefoneInternacional__c', false);
    }

    public override void beforeInsert(){
        Bdrs.Phone.validateAndFormat(this.lstBeneficiariosTelefoneFormat, Beneficiario__c.Telefone__c, false);
    }

    public override void beforeUpdate(){
        Bdrs.Phone.validateAndFormat(this.lstBeneficiariosTelefoneFormat, Beneficiario__c.Telefone__c, false);
    }

}