force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Representante.recordType-meta.xml
<RecordType>
    <fullName>Representante</fullName>
    <active>true</active>
    <description>Tipo de registro criado para receber diferentes filiais dos mesmos representantes.</description>
    <label>Representante</label>
</RecordType>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Representante.cls
public class Representante {

    public List<Id> criarRepresentante(Map<String, User> mapDocumentoRepresentante){
        List<Id> novosRepresentantesIds = new List<Id>();
        try{
            Database.UpsertResult[] results =  Database.upsert(mapDocumentoRepresentante.values(), User.IdExterno__c, true);
            for(Database.UpsertResult result : results){
                if(result.isCreated()){
                    novosRepresentantesIds.add(result.getId());
                }
            }
        }catch (Exception ex){
            throw new RepresentanteException('Erro na criação do Representante: ' + ex.getMessage());
        }
        
        return novosRepresentantesIds;
    }
    @future
    public static void inserirCasos(String casosJson) {
        try {
            List<Case> casosParaInserir = (List<Case>) JSON.deserialize(casosJson, List<Case>.class);
            insert casosParaInserir;
        } catch (Exception e) {
            throw new RepresentanteException('Erro ao criar casos: ' + e.getMessage());
        }
    }

    @future
    public static void criarCodigoProtheus(String mapChaveCodProtheusString){
        try{
            Map<String, CodigoProtheus__c> mapChaveCodProtheus = (Map<String, CodigoProtheus__c>) JSON.deserialize(mapChaveCodProtheusString, Map<String, CodigoProtheus__c>.class);
            Database.upsert(mapChaveCodProtheus.values(), CodigoProtheus__c.IdExterno__c, true);
        }catch (Exception ex){
            throw new RepresentanteException('Erro na criação do Código do Protheus: ' + ex.getMessage());
        }
    }

    /* @future
    public static void inativarCodigosAnteriores(String lstCodProtheusAnterioresString){
        try{
            List<CodigoProtheus__c> lstCodProtheusAnteriores = (List<CodigoProtheus__c>) JSON.deserialize(lstCodProtheusAnterioresString,List<CodigoProtheus__c>.class);
            update lstCodProtheusAnteriores;
        } catch (Exception ex){
            throw new RepresentanteException('Erro na inativação de códigos anteriores: ' + ex.getMessage());
        }
    } */

    public class RepresentanteException extends Exception {}

}