force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CodigoProtheusRepresentantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Representante.recordType-meta.xml
<RecordType>
    <fullName>Representante</fullName>
    <active>true</active>
    <description>Tipo de registro criado para receber diferentes filiais dos mesmos representantes.</description>
    <label>Representante</label>
</RecordType>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RepresentanteTest.cls
@IsTest
private class RepresentanteTest {
    @IsTest
    static void testCriarRepresentante() {

        List<RepresentanteSchema.Representante> representanteRequest = new List<RepresentanteSchema.Representante>{};
        RepresentanteSchema.Representante teste1 = new RepresentanteSchema.Representante();
        List<NegociacaoSchema.Filial> filialRequest = new List<NegociacaoSchema.Filial>{};
        NegociacaoSchema.Filial teste2 = new NegociacaoSchema.Filial();

        teste2.cnpj = '22345678901234';
        teste2.filial = 'teste';
        teste2.razaoSocial = 'teste';
        teste2.codigoEmpresa = '123';
        teste2.codigoFilial = '123';
        teste2.status = true;

        filialRequest.add(teste2);

        teste1.nome = 'Rapha';
        teste1.documento = '12345678901234';
        teste1.email = 'raphael@teste.com';
        teste1.codigoProtheus = 'testeCodigoProtheus';
        teste1.status = true;
        teste1.gerenteResponsavel = 'teste';
        teste1.funcao = 'Gerente de negócio';
        teste1.filial = '123';
        teste1.unidadeNegocio = 'Investimentos';

        representanteRequest.add(teste1);

        RestRequest reqFilial = new RestRequest();
        RestResponse resFilial = new RestResponse();
        reqFilial.requestURI = '/services/apexrest/filial/criarFilial';
        reqFilial.httpMethod = 'POST';

        RestRequest reqRepresentante = new RestRequest();
        RestResponse resRepresentante = new RestResponse();
        reqRepresentante.requestURI = '/services/apexrest/representante/criarUsuario';
        reqRepresentante.httpMethod = 'POST';

        RepresentanteSchema.RepresentantesRequest representante = new RepresentanteSchema.RepresentantesRequest();
        representante.representantes = representanteRequest;

        NegociacaoSchema.FilialRequest filial = new NegociacaoSchema.FilialRequest();
        filial.filialFields = filialRequest;

        Test.startTest();
        RestContext.request = reqFilial;
        RestContext.response = resFilial;
        RestSchema.RestMessageResponse response = FilialRest.criarFilial(filial);

        RestContext.request = reqRepresentante;
        RestContext.response = resRepresentante;
        RepresentanteService service = new RepresentanteService();
        service.criarRepresentantes(representante);
        Test.stopTest();

        List<User> representantesCriados = [SELECT Id, Name FROM User WHERE Name = 'Rapha'];
        List<CodigoProtheus__c> lstCodProtheus = [SELECT Id, Codigo__c, Representante__c FROM CodigoProtheus__c WHERE Codigo__c = 'testeCodigoProtheus'];

        Assert.areEqual(1, representantesCriados.size());
        Assert.areEqual(1, lstCodProtheus.size());
        Assert.areEqual(representantesCriados[0].Id, lstCodProtheus[0].Representante__c);
    }
    
}