force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Código Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Produtos.recordType-meta.xml
<RecordType>
    <fullName>Produtos</fullName>
    <active>true</active>
    <label>Produtos</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <label>Razão social</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DataHoraUltimaAprovacao__c.field-meta.xml
<CustomField>
    <fullName>DataHoraUltimaAprovacao__c</fullName>
    <description>Campo de controle para o processo de aprovação de investimentos.</description>
    <label>Data/hora última aprovação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NegociacaoFactory.cls
public with sharing class NegociacaoFactory {

    public List<Opportunity> atualizarDatasOportunidadesProcessoAprovacao(Map<Id, ProcessInstanceStep> mapOppIdEtapaProcesso){
        List<Opportunity> lstOportunidades = new List<Opportunity>();

        for(Id idOportunidade : mapOppIdEtapaProcesso.keySet()){
            ProcessInstanceStep ultimaEtapa = mapOppIdEtapaProcesso.get(idOportunidade);

            if((ultimaEtapa.StepStatus == 'Approved' && ultimaEtapa.ProcessInstance.LastActor.Funcao__c == 'Vice presidencia') || ultimaEtapa.StepStatus == 'Rejected'){
                Opportunity oportunidade = new Opportunity(
                    DataHoraUltimaAprovacao__c = null,
                    Id = idOportunidade,
                    StageName = ultimaEtapa.StepStatus == 'Rejected' ? 'Taxa/Prazo Reprovada' : 'Taxa/Prazo Aprovada'
                );

                lstOportunidades.add(oportunidade);
            }
        }

        return lstOportunidades;
    }

    public List<Filial__c> gerarObjetosFilial(List<NegociacaoSchema.Filial> filiaisRequest) {
        List<Filial__c> filiais = new List<Filial__c>();
        
        for (NegociacaoSchema.Filial filialRequest : filiaisRequest) {
            String documentoFormatado = Format.documento(filialRequest.cnpj);
            Filial__c filial = new Filial__c(
                CNPJ__C = documentoFormatado,
                CodigoEmpresa__c = filialRequest.codigoEmpresa,
                CodigoFilial__c = filialRequest.codigoFilial,
                Name = filialRequest.filial,
                RazaoSocial__c = filialRequest.razaoSocial,
                Status__c = filialRequest.status,
                IdExterno__c = Bdrs.Format.clearNumberFormatting(filialRequest.cnpj)
            );
            
            filiais.add(filial);
        }
        
        return filiais;
    }

    public List<Product2> gerarObjetoProduto(List<NegociacaoSchema.Produto> produtoRequest){
        List<Product2> produtos = new List<Product2>();

        for(NegociacaoSchema.Produto produtosRequest : produtoRequest){
            Product2 produto = new Product2(
                IsActive = produtosRequest.statusProduto,
                Description = produtosRequest.descricaoProduto,
                Name = produtosRequest.nomeProduto,
                IdExterno__c = produtosRequest.nomeProduto
            );
            produtos.add(produto);
        }

        return produtos;
    }

    public List<CodigoProtheus__c> gerarObjetosProdutosFilial(Map<String, Id> filialCodeToIdMap, Map<String, Id> produtoCodeToIdMap, List<NegociacaoSchema.Produto> produtosRequest) {
        List<CodigoProtheus__c> produtosFiliais = new List<CodigoProtheus__c>();
    
        for(NegociacaoSchema.Produto produtoRequest : produtosRequest){
            for(NegociacaoSchema.Filial filial : produtoRequest.filiais) {
                CodigoProtheus__c produtoFilial = new CodigoProtheus__c();
                produtoFilial.Filial__c = filialCodeToIdMap.get(String.ValueOf(filial.codigoFilial));
                produtoFilial.Produto__c = produtoCodeToIdMap.get(produtoRequest.nomeProduto);
                produtoFilial.Codigo__c = produtoRequest.codigoProduto;
                produtoFilial.IdExterno__c = filial.codigoFilial + ' + ' + produtoRequest.codigoProduto;
                produtoFilial.Ativo__c = produtoRequest.statusProduto;
                produtoFilial.RecordTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Produtos').getRecordTypeId();
                
                produtosFiliais.add(produtoFilial);
            }
        }
    
        return produtosFiliais;
    }

    public List<Approval.ProcessWorkitemRequest> gerarSolicitacoesAprovacao(List<ProcessInstanceWorkItem> listItensPendentes, Map<Id, ProcessInstanceStep> mapOppIdEtapaProcesso){
        List<Approval.ProcessWorkitemRequest> listApprovalRequest = new List<Approval.ProcessWorkitemRequest>();

        for(ProcessInstanceWorkItem item : listItensPendentes){
            Approval.ProcessWorkitemRequest request = new Approval.ProcessWorkitemRequest();
            ProcessInstanceStep ultimaEtapa = mapOppIdEtapaProcesso.get(item.ProcessInstance.TargetObjectId);

            if(ultimaEtapa.StepStatus == 'Rejected' || (ultimaEtapa.StepStatus == 'Approved' && ultimaEtapa.ProcessInstance.LastActor.Funcao__c == 'Vice presidencia')){
                String actionAprovacao = ultimaEtapa.StepStatus == 'Rejected' ? 'Reject' : 'Approve';
                String mensagemAprovacao = ultimaEtapa.StepStatus == 'Rejected' ? 'Reprovado automaticamente.' : 'Aprovado automaticamente pela VP.';

                request.setWorkItemId(item.Id);
                request.setAction(actionAprovacao);
                request.setComments(mensagemAprovacao);
                listApprovalRequest.add(request);
            }
        }

        return listApprovalRequest;
    }

    public List<Approval.ProcessSubmitRequest> validarEnvioAprovacaoVP(Map<Id, Id> mapOppIdVicePresidencia, Map<Id, List<ProcessInstanceWorkitem>> mapOppIdItensPendentes, Map<Id, ProcessInstanceStep> mapOppIdEtapaProcesso){
        List<Approval.ProcessSubmitRequest> lstApprovalReq = new List<Approval.ProcessSubmitRequest>();

        for(Id oppId : mapOppIdEtapaProcesso.keySet()){
            List<ProcessInstanceWorkitem> lstItensPendentes = mapOppIdItensPendentes.get(oppId);
            ProcessInstanceStep ultimaEtapa = mapOppIdEtapaProcesso.get(oppId);

            if(lstItensPendentes == null && ultimaEtapa.StepStatus == 'Approved' && ultimaEtapa.ProcessInstance.LastActor.Funcao__c != 'Vice presidencia'){
                Approval.ProcessSubmitRequest approvalReq = new Approval.ProcessSubmitRequest();
                approvalReq.setObjectId(oppId);
                approvalReq.setProcessDefinitionNameOrId(ultimaEtapa.ProcessInstance.ProcessDefinition.DeveloperName);
                approvalReq.setNextApproverIds(new List<Id>{ mapOppIdVicePresidencia.get(oppId) });
                approvalReq.setSubmitterId(ultimaEtapa.ProcessInstance.CreatedById);

                lstApprovalReq.add(approvalReq);
            }
        }

        return lstApprovalReq;
    }

}