force-app/main/default/objects/InformcoesFinanceirasConta__c/InformcoesFinanceirasConta__c.object-meta.xml
<CustomObject>
    <label>Informações financeiras da conta</label>
    <nameField>
        <label>Informações financeiras da conta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações financeiras da conta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/InfoFinanceirasContaTriggerHandler.cls
public with sharing class InfoFinanceirasContaTriggerHandler extends Bdrs.TriggerHandler{
    
    private CaptacaoClienteService captacaoService = new CaptacaoClienteService();

    private List<InformcoesFinanceirasConta__c> listInfoFinanceirasConta;
    private List<InformcoesFinanceirasConta__c> listInfoFinanceirasContaCelularFormat;
    private List<InformcoesFinanceirasConta__c> listInfoFinanceirasContaTelefoneFormat;

    public InfoFinanceirasContaTriggerHandler(){
        this.listInfoFinanceirasConta = (List<InformcoesFinanceirasConta__c>) Trigger.new;
        this.listInfoFinanceirasContaCelularFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'CelularInternacional__c', false);
        this.listInfoFinanceirasContaTelefoneFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'TelefoneInternacional__c', false);
    }

    public override void beforeInsert(){
        Bdrs.Phone.validateAndFormat(this.listInfoFinanceirasContaTelefoneFormat, InformcoesFinanceirasConta__c.Telefone__c, false);
        Bdrs.Phone.validateAndFormat(this.listInfoFinanceirasContaCelularFormat, InformcoesFinanceirasConta__c.Celular__c, true);
        this.captacaoService.validarInfoFinanceirasContaExistentes(this.listInfoFinanceirasConta);
    }

    public override void beforeUpdate(){
        Bdrs.Phone.validateAndFormat(this.listInfoFinanceirasContaTelefoneFormat, InformcoesFinanceirasConta__c.Telefone__c, false);
        Bdrs.Phone.validateAndFormat(this.listInfoFinanceirasContaCelularFormat, InformcoesFinanceirasConta__c.Celular__c, true);
        this.captacaoService.validarInfoFinanceirasContaExistentes(this.listInfoFinanceirasConta);
    }

}