force-app/main/default/objects/Account/fields/AtivoInvestimentos__c.field-meta.xml
<CustomField>
    <fullName>AtivoInvestimentos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo Investimentos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AtivoOperacesEstruturadas__c.field-meta.xml
<CustomField>
    <fullName>AtivoOperacesEstruturadas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo Operações estruturadas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AtivoProdutosFinanceiros__c.field-meta.xml
<CustomField>
    <fullName>AtivoProdutosFinanceiros__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo Produtos financeiros</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ItemComissionado__mdt/ItemComissionado__mdt.object-meta.xml
<CustomObject>
    <label>Item Comissionado</label>
    <pluralLabel>Itens Comissionado</pluralLabel>
</CustomObject>

force-app/main/default/objects/ItemComissionado__mdt/fields/Comissionamento__c.field-meta.xml
<CustomField>
    <fullName>Comissionamento__c</fullName>
    <label>Comissionamento</label>
    <referenceTo>Comissionamento__mdt</referenceTo>
    <relationshipLabel>Itens Comissionado</relationshipLabel>
    <relationshipName>ItensComissionado</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ItemComissionado__mdt/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
                <default>true</default>
                <label>Gerente de negócio</label>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretoria</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Célula de retenção</fullName>
            </value>
            <value>
                <fullName>Time de relacionamento</fullName>
            </value>
            <value>
                <fullName>Gerente de relacionamento principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ItemComissionado__mdt/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ValorOportunidade__c</fullName>
    <label>Valor da Oportunidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/TimeRelacionamento__c.object-meta.xml
<CustomObject>
    <label>Time de Relacionamento</label>
    <nameField>
        <displayFormat>TMR - {0000}</displayFormat>
        <label>Nome de Time de Relacionamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times de Relacionamento</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeRelacionamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Times de Relacionamento</relationshipLabel>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/DivisaoComissao__c.field-meta.xml
<CustomField>
    <fullName>DivisaoComissao__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Divisão de comissão</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <formula>TEXT(NomeGerente__r.Funcao__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Função</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/GerenteIndicado__c.field-meta.xml
<CustomField>
    <fullName>GerenteIndicado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gerente indicado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/NomeGerente__c.field-meta.xml
<CustomField>
    <fullName>NomeGerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Times de Relacionamento</relationshipLabel>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/ProprietarioOpp__c.field-meta.xml
<CustomField>
    <fullName>ProprietarioOpp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proprietario da Opp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>TEXT( NomeGerente__r.UnidadeNegocio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretor</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Gestor(a)</fullName>
            </value>
            <value>
                <fullName>Analista</fullName>
            </value>
            <value>
                <fullName>Analista SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <label>Unidade de negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operações estruturadas</fullName>
            </value>
            <value>
                <fullName>Investimentos</fullName>
            </value>
            <value>
                <fullName>Produtos financeiros</fullName>
            </value>
            <value>
                <fullName>Formalização</fullName>
            </value>
            <value>
                <fullName>Crédito</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ComissaoRepository.cls
public class ComissaoRepository {
    public List<ItemComissionado__mdt> buscarComissionadosMetadado(String unidadeNegocio, String tipoComissao, String tipoNegociacao) {
        Comissionamento__mdt comissionamento = [
            SELECT 
                Id 
            FROM 
                Comissionamento__mdt 
            WHERE 
                UnidadeNegocio__c = :unidadeNegocio 
            AND TipoComissao__c = :tipoComissao 
            AND TipoNegociacao__c = :tipoNegociacao
        ].get(0);

        return [
            SELECT 
                Funcao__c,
                Percentual__c
            FROM 
                ItemComissionado__mdt
            WHERE
                Comissionamento__c = :comissionamento.Id
        ];
    }

    public List<Opportunity> buscarDetalhesOportunidade(Set<Id> oportunidadesIds) {
        return [
            SELECT 
                Id,
                ValorOportunidade__c,
                UnidadeNegocio__c,
                Type,
                Account.AtivoInvestimentos__c,
                Account.AtivoOperacesEstruturadas__c,
                Account.AtivoProdutosFinanceiros__c,
                (
                    SELECT 
                        Id,
                        Funcao__c,
                        NomeGerente__c,
                        DivisaoComissao__c,
                        Principal__c, //Também recebe comissao. Gerente da Conta  
                        ProprietarioOpp__c, //Proprietário da Oportunidade. A Hierarquia do proprietário que recebe
                        GerenteIndicado__c //Indicação de qualquer pessoa para receber comissão
                    FROM 
                        TimesRelacionamento__r
                )
            FROM 
                Opportunity
            WHERE
                Id IN :oportunidadesIds
        ];
    }

    public List<GroupMember> buscarMembrosGrupo(String grupoDeloperName) { 
        return [
            SELECT 
                Id, 
                UserOrGroupId 
            FROM 
                GroupMember 
            WHERE  
                Group.DeveloperName =: grupoDeloperName
        ];   
    } 
    
    public List<User> buscarHierarquiaUsuario(Id usuarioId) { 
        return [
            SELECT 
                Id, 
                Funcao__c,
                ManagerId, //GG
                Manager.Funcao__c, //Funcao GG
                Manager.ManagerId, //Superindente
                Manager.Manager.Funcao__c, //Funcao Superindente
                Manager.Manager.ManagerId, //Diretor
                Manager.Manager.Manager.Funcao__c, //Fucao Diretor
                Manager.Manager.Manager.ManagerId, //VP
                Manager.Manager.Manager.Manager.Funcao__c //Funcao VP
            FROM 
                User 
            WHERE  
                Id =: usuarioId
        ];   
    } 
}