force-app/main/default/objects/Account/fields/BairroCobranca__c.field-meta.xml
<CustomField>
    <fullName>BairroCobranca__c</fullName>
    <label>Bairro de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComplementoCobranca__c.field-meta.xml
<CustomField>
    <fullName>ComplementoCobranca__c</fullName>
    <label>Complemento de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClienteFactory.cls
public with sharing class ClienteFactory {
    
    public static ClienteSchema buildClienteRequest(Account conta, CodigoProtheus__c representanteProtheus){
        ClienteSchema cliente = new ClienteSchema();
        ClienteSchema.MarketSegment marketSegment = new ClienteSchema.MarketSegment();
        ClienteSchema.GovernmentalInformation governmentalInformation = new ClienteSchema.GovernmentalInformation();
        ClienteSchema.Address address = new ClienteSchema.Address();

        String numerosDocumento = Bdrs.Format.clearNumberFormatting(conta.Documento__c);
        String primeirosNumerosDocumento = numerosDocumento.substring(0, 8);
        String companyInternalId = '01' + representanteProtheus.Filial__r.CodigoEmpresa__c + '   ';
        String documento = conta.RecordType.Name == 'Empresa' ? primeirosNumerosDocumento + '0001' : primeirosNumerosDocumento;
        companyInternalId += documento;        

        cliente.branchId = representanteProtheus.Filial__r.CodigoEmpresa__c + '   ';
        cliente.companyInternalId = companyInternalId;
        cliente.code = primeirosNumerosDocumento;
        cliente.storeId = conta.RecordType.Name == 'Empresa' ? '0001' : numerosDocumento.substring(numerosDocumento.length()-3);
        cliente.shortName = conta.FirstName != null ? Util.removerAcentosCaracteres(conta.FirstName.toUpperCase()) : Util.removerAcentosCaracteres(conta.Name.toUpperCase());
        cliente.name = Util.removerAcentosCaracteres(conta.Name.toUpperCase());
        cliente.type = 1;
        cliente.entityType = conta.RecordType.Name == 'Empresa' ? 'J' : 'F';
        cliente.registerSituation = '2';
        cliente.strategicCustomerType = 'F';
        
        governmentalInformation.id = numerosDocumento;
        governmentalInformation.name = conta.RecordType.Name == 'Empresa' ? 'CNPJ' : 'CPF';

        address.billingAddress = true;
        address.mainAddress = true;
        address.country.countryDescription = conta.BillingCountry?.toUpperCase();
        address.state.stateId = conta.BillingState?.toUpperCase();
        address.state.stateDescription = conta.BillingState?.toUpperCase();
        address.city.cityDescription = Util.removerAcentosCaracteres(conta.BillingCity?.toUpperCase());
        address.address = Util.removerAcentosCaracteres(conta.BillingStreet?.toUpperCase());
        address.zipCode = Bdrs.Format.clearNumberFormatting(conta.BillingPostalCode);
        address.district = Util.removerAcentosCaracteres(conta.BairroCobranca__c);
        address.complement = conta.ComplementoCobranca__c != null ? Util.removerAcentosCaracteres(conta.ComplementoCobranca__c.toUpperCase()) : '';

        cliente.GovernmentalInformation.add(governmentalInformation);
        cliente.address = address;

        return cliente;
    }

    public static CodigoProtheus__c buildCodigoProtheus(Account conta, CodigoProtheus__c representanteProtheus){
        String numerosDocumento = Bdrs.Format.clearNumberFormatting(conta.Documento__c);
        String primeirosNumerosDocumento = numerosDocumento.substring(0, 8);

        CodigoProtheus__c novoCodigoProtheus = new CodigoProtheus__c();
        novoCodigoProtheus.RecordTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Conta').getRecordTypeId();
        novoCodigoProtheus.Codigo__c = primeirosNumerosDocumento;
        novoCodigoProtheus.Empresa__c = representanteProtheus.Filial__r.CodigoEmpresa__c;
        novoCodigoProtheus.Filial__c = representanteProtheus.Filial__c;
        novoCodigoProtheus.Conta__c = conta.Id;
        novoCodigoProtheus.Ativo__c = true;
        novoCodigoProtheus.IdExterno__c = representanteProtheus.Filial__r.CodigoEmpresa__c + ' + ' + primeirosNumerosDocumento;

        return novoCodigoProtheus;
    }
}