force-app/main/default/objects/Account/fields/BairroCobranca__c.field-meta.xml
<CustomField>
    <fullName>BairroCobranca__c</fullName>
    <label>Bairro de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComplementoCobranca__c.field-meta.xml
<CustomField>
    <fullName>ComplementoCobranca__c</fullName>
    <label>Complemento de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Código Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Representante__c.field-meta.xml
<CustomField>
    <fullName>Representante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CodigoProtheusRepresentantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <label>Unidade de negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produtos financeiros</fullName>
            </value>
            <value>
                <fullName>Investimentos</fullName>
            </value>
            <value>
                <fullName>Prime Euro Securitizadora</fullName>
            </value>
            <value>
                <fullName>Operações estruturadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro criado para cadastrar parceiros (PF e PJ)</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Produtos.recordType-meta.xml
<RecordType>
    <fullName>Produtos</fullName>
    <active>true</active>
    <label>Produtos</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Representante.recordType-meta.xml
<RecordType>
    <fullName>Representante</fullName>
    <active>true</active>
    <description>Tipo de registro criado para receber diferentes filiais dos mesmos representantes.</description>
    <label>Representante</label>
</RecordType>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>Número do contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/PropostaProtheus__c.field-meta.xml
<CustomField>
    <fullName>PropostaProtheus__c</fullName>
    <inlineHelpText>Número da proposta cadastrada no Protheus.</inlineHelpText>
    <label>Proposta Protheus</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>RecordType.Name</formula>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/InformacoesFinanceirasOportunidade__c.object-meta.xml
<CustomObject>
    <label>Informações financeiras da oportunidade</label>
    <nameField>
        <displayFormat>IFO-{0000}</displayFormat>
        <label>Informações financeiras da oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações financeiras da oportunidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Informações financeiras da oportunidade</relationshipLabel>
    <relationshipName>InformacoesFinanceirasOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informações financeiras da oportunidade</relationshipLabel>
    <relationshipName>InformacoesFinanceirasOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DataHoraIntegracaoProtheus__c.field-meta.xml
<CustomField>
    <fullName>DataHoraIntegracaoProtheus__c</fullName>
    <description>Campo de controle para registrar os horários dos envios de Oportunidade ganha para o Protheus.</description>
    <label>Data/hora integração Protheus</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>Account.Documento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PropostaProtheus__c.field-meta.xml
<CustomField>
    <fullName>PropostaProtheus__c</fullName>
    <inlineHelpText>Número da proposta cadastrada no Protheus.</inlineHelpText>
    <label>Proposta Protheus</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusProtheus__c.field-meta.xml
<CustomField>
    <fullName>StatusProtheus__c</fullName>
    <defaultValue>&apos;Não integrada&apos;</defaultValue>
    <description>Campo criado para controlar quando uma oportunidade é integrada no Protheus.</description>
    <label>Status Protheus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não integrada</fullName>
            </value>
            <value>
                <fullName>Em processamento</fullName>
            </value>
            <value>
                <fullName>Em reprocessamento</fullName>
            </value>
            <value>
                <fullName>Reprocessada</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/TimeRelacionamento__c.object-meta.xml
<CustomObject>
    <label>Time de Relacionamento</label>
    <nameField>
        <displayFormat>TMR - {0000}</displayFormat>
        <label>Nome de Time de Relacionamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times de Relacionamento</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeRelacionamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Times de Relacionamento</relationshipLabel>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/NomeGerente__c.field-meta.xml
<CustomField>
    <fullName>NomeGerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>TEXT( NomeGerente__r.UnidadeNegocio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Cadastro de parceiros relacionados a Oportunidade</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/TimeRelacionamento__c/recordTypes/TimeRelacionamento.recordType-meta.xml
<RecordType>
    <fullName>TimeRelacionamento</fullName>
    <active>true</active>
    <description>Cadastro dos gerentes relacionados à oportunidade</description>
    <label>Time de relacionamento</label>
</RecordType>

force-app/main/default/classes/ProtheusOportunidadeGanhaWorkRun.cls
global class ProtheusOportunidadeGanhaWorkRun implements Bdrs.WorkRun {
    
    private FormalizacaoFactory factory = new FormalizacaoFactory();
    private FormalizacaoRepository repository = new FormalizacaoRepository();

    global String process(String content){
        Id oportunidadeId = (Id) JSON.deserialize(content, Id.class);
        Id idParceiroRelacionado;
        CodigoProtheus__c codigoProtheusConta;
        CodigoProtheus__c codigoProtheusParceiro;
        CodigoProtheus__c codigoProtheusProduto;
        CodigoProtheus__c codigoProtheusRepresentante;
        Map<Id, CodigoProtheus__c> mapIdComissionadoCodigoProtheus = new Map<Id, CodigoProtheus__c>();
        Map<Id, TimeRelacionamento__c> mapComissionados = new Map<Id, TimeRelacionamento__c>();
        Map<String, CodigoProtheus__c> mapCodigosProtheus = new Map<String, CodigoProtheus__c>();

        Opportunity oportunidade = this.repository.buscarDadosOportunidadeGanha(oportunidadeId);
        Quote cotacao = this.repository.buscarDadosCotacaoOportunidadeId(oportunidadeId);
        List<TimeRelacionamento__c>  lstTimeRelacionamento = this.repository.buscarTimesRelacionamentoOportunidadeId(oportunidadeId);

        for(TimeRelacionamento__c timeRelacionamento : lstTimeRelacionamento){
            if(timeRelacionamento.RecordType.Name == 'Parceiro')
                idParceiroRelacionado  = timeRelacionamento.Conta__c;
            else
                mapComissionados.put(timeRelacionamento.NomeGerente__c, timeRelacionamento);
        }

        List<CodigoProtheus__c> lstCodigosProtheus = this.repository.buscarCodigosProtheusOportunidadeGanha(idParceiroRelacionado, oportunidade.Produto__c);
        List<InformacoesFinanceirasOportunidade__c> listInformacoesFinanceirasOportunidade = oportunidade.InformacoesFinanceirasOportunidade__r;

        for(CodigoProtheus__c codigoProtheus : lstCodigosProtheus)
            mapCodigosProtheus.put(codigoProtheus.RecordType.Name, codigoProtheus);

        codigoProtheusParceiro = mapCodigosProtheus.get('Parceiro');
        codigoProtheusProduto = mapCodigosProtheus.get('Produtos');
        codigoProtheusConta = this.repository.buscarCodigoProtheusFilialContaId(codigoProtheusProduto.Filial__r.CodigoFilial__c, oportunidade.AccountId);
        codigoProtheusRepresentante = this.repository.buscarCodigoProtheusFilialRepresentanteId(codigoProtheusProduto.Filial__r.CodigoFilial__c, oportunidade.OwnerId);

        List<CodigoProtheus__c> lstCodigosProtheusComissionados = this.repository.buscarCodigosProtheusFiliaisRepresentantesIds(new Set<String> { codigoProtheusProduto.Filial__r.CodigoFilial__c }, mapComissionados.keySet());

        for(CodigoProtheus__c codigoProtheus : lstCodigosProtheusComissionados){
            for(TimeRelacionamento__c comissionado : mapComissionados.values()){
                if(comissionado.NomeGerente__c == codigoProtheus.Representante__c){
                    mapIdComissionadoCodigoProtheus.put(comissionado.Id, codigoProtheus);
                    break;
                }
            }
        }

        if(codigoProtheusRepresentante == null)
           return 'Oportunidade ' + oportunidadeId + ' não foi enviada devido à ausência de Código Protheus do representante relacionado. Consulte o time de T.I para inserção via Protheus.';
        else if(codigoProtheusConta == null){
            Account conta = [SELECT Id, Documento__c, RecordType.Name, Name, FirstName, BillingCountry, BillingState, BillingCity, BillingStreet, BillingPostalCode, BairroCobranca__c, ComplementoCobranca__c FROM Account WHERE Id =: oportunidade.AccountId];

            SendClienteWorkRunSchema.Request sendClienteWorkRunObj = new SendClienteWorkRunSchema.Request();
            sendClienteWorkRunObj.clienteRequest = ClienteFactory.buildClienteRequest(conta, codigoProtheusRepresentante);
            sendClienteWorkRunObj.codigoProtheus = ClienteFactory.buildCodigoProtheus(conta, codigoProtheusRepresentante);
            sendClienteWorkRunObj.oportunidade = oportunidade;

            Bdrs.WorkControl.createOutboundWork(SendClienteWorkRun.class, JSON.serialize(sendClienteWorkRunObj));
            Bdrs.WorkControl.save();

            return 'Oportunidade ' + oportunidadeId + ' não foi enviada devido à ausência de Código Protheus do cliente relacionado. Status: Fila de reprocessamento.';
        } else if(oportunidade.UnidadeNegocio__c == 'Produtos financeiros' && codigoProtheusParceiro == null && idParceiroRelacionado != null){
            IntegracaoClienteParceiroInvocable.Request invocableRequest = new IntegracaoClienteParceiroInvocable.Request();
            List<IntegracaoClienteParceiroInvocable.Request> lstInvocableRequest = new List<IntegracaoClienteParceiroInvocable.Request>();
            invocableRequest.idConta = idParceiroRelacionado;
            invocableRequest.oportunidade = oportunidade;

            lstInvocableRequest.add(invocableRequest);

            IntegracaoClienteParceiroInvocable.integrarClienteParceiroProtheus(lstInvocableRequest);

            return 'Oportunidade ' + oportunidadeId + ' não foi enviada devido à ausência de Código Protheus do parceiro relacionado. Status: Fila de reprocessamento.';
        } else{
            FormalizacaoSchema.ProtheusOportunidadeGanhaSalesforceRequest objSalesforceRequest = new FormalizacaoSchema.ProtheusOportunidadeGanhaSalesforceRequest(codigoProtheusConta, codigoProtheusRepresentante, listInformacoesFinanceirasOportunidade, mapIdComissionadoCodigoProtheus, mapComissionados, mapCodigosProtheus, oportunidade, cotacao);
            String objOppGanhaRequestStr = this.factory.construirObjProtheusOportunidadeGanhaRequest(objSalesforceRequest);
            System.debug(objOppGanhaRequestStr);
    
            FormalizacaoSchema.ProtheusIntegracaoOportunidadeGanhaResponse objOppGanhaResponse = this.repository.integrarOportunidadeGanhaProtheus(objOppGanhaRequestStr);
            return JSON.serialize(objOppGanhaResponse);
        }
   
    }

    global String processResponse(String content, String responseContent){
        Id oportunidadeId = (Id) JSON.deserialize(content, Id.class);
        Opportunity oportunidade = new Opportunity(Id = oportunidadeId);
        Contrato__c contrato = this.repository.buscarContratoRelacionadoOportunidadeId(oportunidadeId);

        if(responseContent.contains('Fila de reprocessamento')){
            oportunidade.DataHoraIntegracaoProtheus__c = Datetime.now();
            oportunidade.StatusProtheus__c = 'Em reprocessamento';
        } else if(!responseContent.contains('Consulte o time de T.I')){
            FormalizacaoSchema.ProtheusIntegracaoOportunidadeGanhaResponse objResponse = (FormalizacaoSchema.ProtheusIntegracaoOportunidadeGanhaResponse) JSON.deserialize(responseContent, FormalizacaoSchema.ProtheusIntegracaoOportunidadeGanhaResponse.class);

            if(objResponse.PROPOSALCODE != null){
                oportunidade.DataHoraIntegracaoProtheus__c = Datetime.now();
                oportunidade.PropostaProtheus__c = objResponse.PROPOSALCODE;
                oportunidade.StatusProtheus__c = 'Integrada';

                if(contrato != null)
                    contrato.PropostaProtheus__c = objResponse.PROPOSALCODE;
            }
        }
  
        update oportunidade;

        if(contrato != null)
            update contrato;

        return responseContent;
	}

}