force-app/main/default/objects/Account/fields/BairroCobranca__c.field-meta.xml
<CustomField>
    <fullName>BairroCobranca__c</fullName>
    <label>Bairro de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComplementoCobranca__c.field-meta.xml
<CustomField>
    <fullName>ComplementoCobranca__c</fullName>
    <label>Complemento de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroCobranca__c.field-meta.xml
<CustomField>
    <fullName>NumeroCobranca__c</fullName>
    <description>Campo criado para preenchimento de endereço completo para envio de oportunidades para sistemas da Euro.</description>
    <label>Número de cobrança</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/StatusConta__c.field-meta.xml
<CustomField>
    <fullName>StatusConta__c</fullName>
    <label>Status Conta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro criado para cadastrar parceiros (PF e PJ)</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>Account.Documento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegracaoClienteParceiroInvocable.cls
public with sharing class IntegracaoClienteParceiroInvocable {
    
    private static ParceiroFactory parceiroFactory = new ParceiroFactory();

    // Define um método invocável
    @InvocableMethod(label='Integrar Cliente e Parceiro Protheus' description='Integra Cliente ou Parceiro no Protheus quando oportunidade ganha')
    public static void integrarClienteParceiroProtheus(List<Request> requests){
        Account conta = new Account();
        Filial__c filial = new Filial__c();
        List<CodigoProtheus__c> lstCodProtheus = new List<CodigoProtheus__c>();
        Set<Id> setFilialId = new Set<Id>();

        //Integração de parceiros
        if(!String.isBlank(requests[0].idConta)) {
            conta = [SELECT Id, Documento__c, Name, FirstName, BairroCobranca__c, BillingAddress, ComplementoCobranca__c, NumeroCobranca__c, OwnerId, StatusConta__c FROM Account WHERE Id =: requests[0].idConta];
            filial = [SELECT Id, CodigoEmpresa__c, CodigoFilial__c FROM Filial__c WHERE CodigoFilial__c = '01001' LIMIT 1];
            List<CodigoProtheus__c> codigosProtheus = filial != null ? [SELECT Id FROM CodigoProtheus__c WHERE RecordType.DeveloperName = 'Parceiro' AND Conta__c =: conta.Id AND Filial__c =: filial.Id] : new List<CodigoProtheus__c>();

            if(codigosProtheus.isEmpty() && filial != null){
                ParceiroSchema.ParceiroWorkRunRequest parceiroSchema = new ParceiroSchema.ParceiroWorkRunRequest();
                parceiroSchema.codigoProtheus = parceiroFactory.buildCodigoProtheus(conta, filial);
                parceiroSchema.parceiroRequest = parceiroFactory.buildParceiroRequest(conta, filial);
                parceiroSchema.oportunidade = requests[0].oportunidade;

                Bdrs.WorkControl.createOutboundWork(SendParceiroWorkRun.class, JSON.serialize(parceiroSchema));
                Bdrs.WorkControl.save();
            }
        }       
    }

    public class Request {
        @InvocableVariable(label='ID da Conta')
        public String idConta;

        @InvocableVariable(label='Oportunidade')
        public Opportunity oportunidade;
    }
}