force-app/main/default/objects/Account/fields/BairroCobranca__c.field-meta.xml
<CustomField>
    <fullName>BairroCobranca__c</fullName>
    <label>Bairro de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComplementoCobranca__c.field-meta.xml
<CustomField>
    <fullName>ComplementoCobranca__c</fullName>
    <label>Complemento de cobrança</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroCobranca__c.field-meta.xml
<CustomField>
    <fullName>NumeroCobranca__c</fullName>
    <description>Campo criado para preenchimento de endereço completo para envio de oportunidades para sistemas da Euro.</description>
    <label>Número de cobrança</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/StatusConta__c.field-meta.xml
<CustomField>
    <fullName>StatusConta__c</fullName>
    <label>Status Conta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro criado para cadastrar parceiros (PF e PJ)</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParceiroFactory.cls
public class ParceiroFactory {
    
    public CodigoProtheus__c buildCodigoProtheus(Account conta, Filial__c filial){
        String primeirosNumerosDocumento = Bdrs.Format.clearNumberFormatting(conta.Documento__c).substring(0,6);

        CodigoProtheus__c codigoProtheus = new CodigoProtheus__c();
        codigoProtheus.Ativo__c = true;
        codigoProtheus.Codigo__c = primeirosNumerosDocumento;
        codigoProtheus.Conta__c = conta.Id;
        codigoProtheus.Filial__c = filial.Id;
        codigoProtheus.IdExterno__c = filial.CodigoFilial__c + '|' + primeirosNumerosDocumento;
        codigoProtheus.RecordTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Parceiro').getRecordTypeId();

        return codigoProtheus;
    }

    public ParceiroSchema.Request buildParceiroRequest(Account conta, Filial__c filial){
        ParceiroSchema.Request parceiroRequest = new ParceiroSchema.Request();
        parceiroRequest.active = conta.StatusConta__c == 'Inativo' ? false : true;
        parceiroRequest.branchId = filial.CodigoFilial__c;
        parceiroRequest.code = Bdrs.Format.clearNumberFormatting(conta.Documento__c).substring(0,6);
        parceiroRequest.companyId = filial.CodigoEmpresa__c;
        parceiroRequest.companyInternalId = filial.CodigoEmpresa__c + filial.CodigoFilial__c;
        parceiroRequest.internalId = filial.CodigoFilial__c + parceiroRequest.code;
        parceiroRequest.name = Util.removerAcentosCaracteres(conta.Name.toUpperCase());
        parceiroRequest.shortName = !String.isBlank(conta.FirstName) ? Util.removerAcentosCaracteres(conta.FirstName.toUpperCase()) : Util.removerAcentosCaracteres(conta.Name.toUpperCase());

        ParceiroSchema.Address parceiroAddress = new ParceiroSchema.Address();
        ParceiroSchema.City parceiroCity = new ParceiroSchema.City();
        ParceiroSchema.Country parceiroCountry = new ParceiroSchema.Country();
        ParceiroSchema.State parceiroState = new ParceiroSchema.State();
        String codigoPostal = conta.BillingAddress?.getPostalCode() != null ? Bdrs.Format.clearNumberFormatting(conta.BillingAddress.getPostalCode()) : '';

        parceiroCity.cityId = conta.BillingAddress?.getCity() != null ? Util.removerAcentosCaracteres(conta.BillingAddress.getCity().toUpperCase()) : '';
        parceiroCountry.countryId = '105';
        parceiroState.stateId = conta.BillingAddress?.getState() != null ? conta.BillingAddress.getState().toUpperCase() : '';

        parceiroAddress.address = conta.BillingAddress?.getStreet() != null ? Util.removerAcentosCaracteres(conta.BillingAddress.getStreet().toUpperCase()) : '';
        parceiroAddress.address = parceiroAddress.address != null && conta.NumeroCobranca__c != null ? parceiroAddress.address + ', ' +  + ', ' + conta.NumeroCobranca__c : parceiroAddress.address;
        parceiroAddress.billingAddress =  true;
        parceiroAddress.city = parceiroCity;
        parceiroAddress.complement = conta.ComplementoCobranca__c != null ? Util.removerAcentosCaracteres(conta.ComplementoCobranca__c.toUpperCase()) : '';
        parceiroAddress.country = parceiroCountry;
        parceiroAddress.district = conta.BairroCobranca__c != null ? Util.removerAcentosCaracteres(conta.BairroCobranca__c.toUpperCase()) : '';
        parceiroAddress.mainAddress = true;
        parceiroAddress.shippingAddress = false;
        parceiroAddress.state = parceiroState;
        parceiroAddress.zipCode = codigoPostal;
        parceiroRequest.address = parceiroAddress;

        return parceiroRequest;
    }

}