force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DadoBancario__c/DadoBancario__c.object-meta.xml
<CustomObject>
    <label>Dado bancário</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Dado bancário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados bancários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DadoBancario__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/DV__c.field-meta.xml
<CustomField>
    <fullName>DV__c</fullName>
    <label>DV</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/InstituicaoFinanceira__c.field-meta.xml
<CustomField>
    <fullName>InstituicaoFinanceira__c</fullName>
    <label>Instituição Financeira</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
                <label>001-Banco do Brasil S.A.</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003-Banco da Amazônia S.A.</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004-Banco do Nordeste do Brasil S.A.</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007-Banco Nacional de Desenvolvimento Econômico e Social - BNDES</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012-Banco Inbursa S.A.</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014-State Street Brasil S.A. - Banco Comercial</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017-BNY Mellon Banco S.A.</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021-BANESTES S.A. Banco do Estado do Espírito Santo</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024-Banco BANDEPE S.A.</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025-Banco Alfa S.A.</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029-Banco Itaú Consignado S.A.</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033-Banco Santander (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036-Banco Bradesco BBI S.A.</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037-Banco do Estado do Pará S.A.</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040-Banco Cargill S.A.</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041-Banco do Estado do Rio Grande do Sul S.A.</label>
            </value>
            <value>
                <fullName>047</fullName>
                <label>047-Banco do Estado de Sergipe S.A.</label>
            </value>
            <value>
                <fullName>062</fullName>
                <label>062-Hipercard Banco Múltiplo S.A.</label>
            </value>
            <value>
                <fullName>063</fullName>
                <label>063-Banco Bradescard S.A.</label>
            </value>
            <value>
                <fullName>065</fullName>
                <label>065-Banco Andbank (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>066</fullName>
                <label>066-Banco Morgan Stanley S.A.</label>
            </value>
            <value>
                <fullName>070</fullName>
                <label>070-BRB - Banco de Brasília S.A.</label>
            </value>
            <value>
                <fullName>074</fullName>
                <label>074-Banco J. Safra S.A.</label>
            </value>
            <value>
                <fullName>077</fullName>
                <label>077-Banco Inter S.A.</label>
            </value>
            <value>
                <fullName>082</fullName>
                <label>082-Banco Topázio S.A.</label>
            </value>
            <value>
                <fullName>083</fullName>
                <label>083-Banco da China Brasil S.A.</label>
            </value>
            <value>
                <fullName>084</fullName>
                <label>084-Sisprime do Brasil</label>
            </value>
            <value>
                <fullName>094</fullName>
                <label>094-Banco Finaxis S.A.</label>
            </value>
            <value>
                <fullName>095</fullName>
                <label>095-Travelex Banco de Câmbio S.A.</label>
            </value>
            <value>
                <fullName>096</fullName>
                <label>096-Banco B3 S.A.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Dados bancários</relationshipLabel>
    <relationshipName>DadosBancarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/InformcoesFinanceirasConta__c.object-meta.xml
<CustomObject>
    <label>Informações financeiras da conta</label>
    <nameField>
        <label>Informações financeiras da conta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações financeiras da conta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/ContaRelacionada__c.field-meta.xml
<CustomField>
    <fullName>ContaRelacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informações financeiras da conta</relationshipLabel>
    <relationshipName>InformacoesFinanceirasConta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informar CPF para pessoa física ou CNPJ pessoa jurídica</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/InstituicaoFinaneira__c.field-meta.xml
<CustomField>
    <fullName>InstituicaoFinaneira__c</fullName>
    <label>Instituição Financeira</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
                <label>001-Banco do Brasil S.A.</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003-Banco da Amazônia S.A.</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004-Banco do Nordeste do Brasil S.A.</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007-Banco Nacional de Desenvolvimento Econômico e Social - BNDES</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012-Banco Inbursa S.A.</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014-State Street Brasil S.A. - Banco Comercial</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017-BNY Mellon Banco S.A.</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021-BANESTES S.A. Banco do Estado do Espírito Santo</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024-Banco BANDEPE S.A.</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025-Banco Alfa S.A.</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029-Banco Itaú Consignado S.A.</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033-Banco Santander (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036-Banco Bradesco BBI S.A.</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037-Banco do Estado do Pará S.A.</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040-Banco Cargill S.A.</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041-Banco do Estado do Rio Grande do Sul S.A.</label>
            </value>
            <value>
                <fullName>047</fullName>
                <label>047-Banco do Estado de Sergipe S.A.</label>
            </value>
            <value>
                <fullName>062</fullName>
                <label>062-Hipercard Banco Múltiplo S.A.</label>
            </value>
            <value>
                <fullName>063</fullName>
                <label>063-Banco Bradescard S.A.</label>
            </value>
            <value>
                <fullName>065</fullName>
                <label>065-Banco Andbank (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>066</fullName>
                <label>066-Banco Morgan Stanley S.A.</label>
            </value>
            <value>
                <fullName>070</fullName>
                <label>070-BRB - Banco de Brasília S.A.</label>
            </value>
            <value>
                <fullName>074</fullName>
                <label>074-Banco J. Safra S.A.</label>
            </value>
            <value>
                <fullName>077</fullName>
                <label>077-Banco Inter S.A.</label>
            </value>
            <value>
                <fullName>082</fullName>
                <label>082-Banco Topázio S.A.</label>
            </value>
            <value>
                <fullName>083</fullName>
                <label>083-Banco da China Brasil S.A.</label>
            </value>
            <value>
                <fullName>084</fullName>
                <label>084-Sisprime do Brasil</label>
            </value>
            <value>
                <fullName>094</fullName>
                <label>094-Banco Finaxis S.A.</label>
            </value>
            <value>
                <fullName>095</fullName>
                <label>095-Travelex Banco de Câmbio S.A.</label>
            </value>
            <value>
                <fullName>096</fullName>
                <label>096-Banco B3 S.A.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/recordTypes/DadoBancario.recordType-meta.xml
<RecordType>
    <fullName>DadoBancario</fullName>
    <active>true</active>
    <description>Cadastro de dados bancários relacionadas à conta.</description>
    <label>Dado bancário</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informe o CPF para Pessoa Física ou CNPJ para Pessoa Jurídica.</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaptacaoClienteTest.cls
@IsTest
private class CaptacaoClienteTest {

    @TestSetup
    static void makeData(){
        Id dadoBancarioRecTypeId = Schema.SObjectType.InformcoesFinanceirasConta__c.getRecordTypeInfosByDeveloperName().get('DadoBancario').getRecordTypeId();
        List<Account> listContas = new List<Account>();
        List<InformcoesFinanceirasConta__c> listInfoFinanceirasConta = new List<InformcoesFinanceirasConta__c>();
        
        Account account1 = new Account(Name = 'Conta 1', Documento__c = '24.080.114/0001-57');
        listContas.add(account1);

        Account account2 = new Account(Name = 'Conta 2', Documento__c = '933.458.940-09');
        listContas.add(account2);

        insert listContas;

        List<Account> listContasInseridas = [SELECT Id FROM Account ORDER BY Documento__c ASC];

        for(Integer i = 0; i < listContasInseridas.size(); i++){
            InformcoesFinanceirasConta__c infoFinanceira = new InformcoesFinanceirasConta__c(
                ContaRelacionada__c = listContasInseridas[i].Id,
                InstituicaoFinaneira__c = '001',
                Agencia__c = '000' + (i + 1),
                Conta__c = '3232' + (i + 1),
                DV__c = String.valueOf(i + 1),
                RecordTypeId = dadoBancarioRecTypeId
            );
            listInfoFinanceirasConta.add(infoFinanceira);
        }

        insert listInfoFinanceirasConta;

        Lead lead = new Lead(FirstName = 'Teste', LastName = 'Lead', Documento__c = '69741379072', LeadSource = 'Site Euro Securitizadora');
        insert lead;

        DadoBancario__c dadoBancario = new DadoBancario__c(Lead__c = lead.Id, InstituicaoFinanceira__c = '001', Agencia__c = '0001', Conta__c = '50500', DV__c = '1');
        insert dadoBancario;
    }

    @IsTest
    static void testVerificarContaExistente() {
        String mensagemErro = '';
        Account account1 = new Account(Name = 'Conta 1', Documento__c = '24.080.114/0001-57');
        Account account2 = new Account(Name = 'Conta 2', Documento__c = '933.458.940-09');

        try {
            //Teste criação de conta com o mesmo documento
            insert account1;
            insert account2;
            
        } catch (Exception ex) {
            mensagemErro = ex.getMessage();
        }

        Assert.isTrue(mensagemErro.contains('Cliente já existente na base'));
    }

    @IsTest
    public static void testFormatarDocumentoLead() {
        List<Lead> testLeads = new List<Lead>();

        Lead lead1 = new Lead();
        lead1.LastName = 'Test';
        lead1.Documento__c = '12345678901234';
        lead1.LeadSource = 'Outra Origem';
        testLeads.add(lead1);

        Lead lead2 = new Lead();
        lead2.LastName = 'Test';
        lead2.Documento__c = '12345678901';
        lead2.LeadSource = 'Site Euro Securitizadora';
        testLeads.add(lead2);

        Lead lead3 = new Lead();
        lead3.LastName = 'Test';
        lead3.Documento__c = '12312312332';
        lead3.LeadSource = 'Site Euro Securitizadora';
        testLeads.add(lead3);
        
        Lead lead4 = new Lead();
        lead4.LastName = 'Test';
        lead4.Documento__c = null;
        testLeads.add(lead4);

        Test.startTest();
        
        CaptacaoClienteService captacaoCliente = new CaptacaoClienteService();
        captacaoCliente.formatarDocumentoLead(testLeads);

        Assert.areEqual('12.345.678/9012-34', testLeads[0].Documento__c);
        Assert.areEqual('123.456.789-01', testLeads[1].Documento__c);
        Assert.areEqual('123.123.123-32', testLeads[2].Documento__c);
        
        Test.stopTest();
    }

    @IsTest
    static void verificarDadosBancariosExistentes(){
        Lead lead = [SELECT Id FROM Lead WHERE Documento__c = '697.413.790-72' LIMIT 1];
        
        DadoBancario__c dadoBancario = new DadoBancario__c(
            Lead__c = lead.Id,
            InstituicaoFinanceira__c = '001',
            Agencia__c = '0001',
            Conta__c = '50500',
            DV__c = '1'
        );

        try{
            insert dadoBancario;
        } catch(Exception ex){
            Assert.isTrue(ex.getMessage().contains('Já existe um registro de Dado bancário para este lead com as mesmas informações de instituição financeira, agência, conta e DV fornecidas.'));
        }
    }

    @IsTest
    static void verificarDadosBancariosMesmaTransacao(){
        Lead lead = [SELECT Id FROM Lead WHERE Documento__c = '697.413.790-72' LIMIT 1];
        List<DadoBancario__c> listDadosBancarios = new List<DadoBancario__c>();

        for(Integer i = 1; i < 3; i++){
            DadoBancario__c dadoBancario = new DadoBancario__c(
                Lead__c = lead.Id,
                InstituicaoFinanceira__c = '001',
                Agencia__c = '0001',
                Conta__c = '50500',
                DV__c = '2'
            );

            listDadosBancarios.add(dadoBancario);
        }

        try{
            insert listDadosBancarios;
        } catch(Exception ex){
            Assert.isTrue(ex.getMessage().contains('Já existe um registro de Dado bancário para este lead com as mesmas informações de instituição financeira, agência, conta e DV fornecidas nesta mesma transação.'));
        }
    }

    @IsTest
    static void verificarInformacoesFinanceirasExistentes(){
        Account conta = [SELECT Id FROM Account WHERE Documento__c = '24.080.114/0001-57' LIMIT 1];
        Id dadoBancarioRecTypeId = Schema.SObjectType.InformcoesFinanceirasConta__c.getRecordTypeInfosByDeveloperName().get('DadoBancario').getRecordTypeId();

        InformcoesFinanceirasConta__c infoFinanceira = new InformcoesFinanceirasConta__c(
            ContaRelacionada__c = conta.Id,
            InstituicaoFinaneira__c = '001',
            Agencia__c = '0001',
            Conta__c = '32321',
            DV__c = '1',
            RecordTypeId = dadoBancarioRecTypeId
        );

        try{
            insert infoFinanceira;
        } catch(Exception ex){
            Assert.isTrue(ex.getMessage().contains('Já existe um registro de Dado bancário para este cliente com as mesmas informações de instituição financeira, agência, conta e DV fornecidas.'));
        }
    }

    @IsTest
    static void verificarInformacoesFinanceirasMesmaTransacao(){
        Account conta = [SELECT Id FROM Account WHERE Documento__c = '933.458.940-09' LIMIT 1];
        Id dadoBancarioRecTypeId = Schema.SObjectType.InformcoesFinanceirasConta__c.getRecordTypeInfosByDeveloperName().get('DadoBancario').getRecordTypeId();
        List<InformcoesFinanceirasConta__c> listInfoFinanceirasConta = new List<InformcoesFinanceirasConta__c>();

        for(Integer i = 1; i < 3; i++){
            InformcoesFinanceirasConta__c infoFinanceira = new InformcoesFinanceirasConta__c(
                ContaRelacionada__c = conta.Id,
                InstituicaoFinaneira__c = '001',
                Agencia__c = '0002',
                Conta__c = '32322',
                DV__c = '3',
                RecordTypeId = dadoBancarioRecTypeId
            );

            listInfoFinanceirasConta.add(infoFinanceira);
        }

        try{
            insert listInfoFinanceirasConta;
        } catch(Exception ex){
            Assert.isTrue(ex.getMessage().contains('Já existe um registro de Dado bancário para este cliente com as mesmas informações de instituição financeira, agência, conta e DV fornecidas nesta mesma transação.'));
        }
    }

}