force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DadoBancario__c/DadoBancario__c.object-meta.xml
<CustomObject>
    <label>Dado bancário</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Dado bancário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados bancários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DadoBancario__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/DV__c.field-meta.xml
<CustomField>
    <fullName>DV__c</fullName>
    <label>DV</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/InstituicaoFinanceira__c.field-meta.xml
<CustomField>
    <fullName>InstituicaoFinanceira__c</fullName>
    <label>Instituição Financeira</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
                <label>001-Banco do Brasil S.A.</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003-Banco da Amazônia S.A.</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004-Banco do Nordeste do Brasil S.A.</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007-Banco Nacional de Desenvolvimento Econômico e Social - BNDES</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012-Banco Inbursa S.A.</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014-State Street Brasil S.A. - Banco Comercial</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017-BNY Mellon Banco S.A.</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021-BANESTES S.A. Banco do Estado do Espírito Santo</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024-Banco BANDEPE S.A.</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025-Banco Alfa S.A.</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029-Banco Itaú Consignado S.A.</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033-Banco Santander (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036-Banco Bradesco BBI S.A.</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037-Banco do Estado do Pará S.A.</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040-Banco Cargill S.A.</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041-Banco do Estado do Rio Grande do Sul S.A.</label>
            </value>
            <value>
                <fullName>047</fullName>
                <label>047-Banco do Estado de Sergipe S.A.</label>
            </value>
            <value>
                <fullName>062</fullName>
                <label>062-Hipercard Banco Múltiplo S.A.</label>
            </value>
            <value>
                <fullName>063</fullName>
                <label>063-Banco Bradescard S.A.</label>
            </value>
            <value>
                <fullName>065</fullName>
                <label>065-Banco Andbank (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>066</fullName>
                <label>066-Banco Morgan Stanley S.A.</label>
            </value>
            <value>
                <fullName>070</fullName>
                <label>070-BRB - Banco de Brasília S.A.</label>
            </value>
            <value>
                <fullName>074</fullName>
                <label>074-Banco J. Safra S.A.</label>
            </value>
            <value>
                <fullName>077</fullName>
                <label>077-Banco Inter S.A.</label>
            </value>
            <value>
                <fullName>082</fullName>
                <label>082-Banco Topázio S.A.</label>
            </value>
            <value>
                <fullName>083</fullName>
                <label>083-Banco da China Brasil S.A.</label>
            </value>
            <value>
                <fullName>084</fullName>
                <label>084-Sisprime do Brasil</label>
            </value>
            <value>
                <fullName>094</fullName>
                <label>094-Banco Finaxis S.A.</label>
            </value>
            <value>
                <fullName>095</fullName>
                <label>095-Travelex Banco de Câmbio S.A.</label>
            </value>
            <value>
                <fullName>096</fullName>
                <label>096-Banco B3 S.A.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Dados bancários</relationshipLabel>
    <relationshipName>DadosBancarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/InformcoesFinanceirasConta__c.object-meta.xml
<CustomObject>
    <label>Informações financeiras da conta</label>
    <nameField>
        <label>Informações financeiras da conta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações financeiras da conta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/ContaRelacionada__c.field-meta.xml
<CustomField>
    <fullName>ContaRelacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informações financeiras da conta</relationshipLabel>
    <relationshipName>InformacoesFinanceirasConta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informar CPF para pessoa física ou CNPJ pessoa jurídica</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/InstituicaoFinaneira__c.field-meta.xml
<CustomField>
    <fullName>InstituicaoFinaneira__c</fullName>
    <label>Instituição Financeira</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
                <label>001-Banco do Brasil S.A.</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003-Banco da Amazônia S.A.</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004-Banco do Nordeste do Brasil S.A.</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007-Banco Nacional de Desenvolvimento Econômico e Social - BNDES</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012-Banco Inbursa S.A.</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014-State Street Brasil S.A. - Banco Comercial</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017-BNY Mellon Banco S.A.</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021-BANESTES S.A. Banco do Estado do Espírito Santo</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024-Banco BANDEPE S.A.</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025-Banco Alfa S.A.</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029-Banco Itaú Consignado S.A.</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033-Banco Santander (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036-Banco Bradesco BBI S.A.</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037-Banco do Estado do Pará S.A.</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040-Banco Cargill S.A.</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041-Banco do Estado do Rio Grande do Sul S.A.</label>
            </value>
            <value>
                <fullName>047</fullName>
                <label>047-Banco do Estado de Sergipe S.A.</label>
            </value>
            <value>
                <fullName>062</fullName>
                <label>062-Hipercard Banco Múltiplo S.A.</label>
            </value>
            <value>
                <fullName>063</fullName>
                <label>063-Banco Bradescard S.A.</label>
            </value>
            <value>
                <fullName>065</fullName>
                <label>065-Banco Andbank (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>066</fullName>
                <label>066-Banco Morgan Stanley S.A.</label>
            </value>
            <value>
                <fullName>070</fullName>
                <label>070-BRB - Banco de Brasília S.A.</label>
            </value>
            <value>
                <fullName>074</fullName>
                <label>074-Banco J. Safra S.A.</label>
            </value>
            <value>
                <fullName>077</fullName>
                <label>077-Banco Inter S.A.</label>
            </value>
            <value>
                <fullName>082</fullName>
                <label>082-Banco Topázio S.A.</label>
            </value>
            <value>
                <fullName>083</fullName>
                <label>083-Banco da China Brasil S.A.</label>
            </value>
            <value>
                <fullName>084</fullName>
                <label>084-Sisprime do Brasil</label>
            </value>
            <value>
                <fullName>094</fullName>
                <label>094-Banco Finaxis S.A.</label>
            </value>
            <value>
                <fullName>095</fullName>
                <label>095-Travelex Banco de Câmbio S.A.</label>
            </value>
            <value>
                <fullName>096</fullName>
                <label>096-Banco B3 S.A.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informe o CPF para Pessoa Física ou CNPJ para Pessoa Jurídica.</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ProdutoNegociar__c.field-meta.xml
<CustomField>
    <fullName>ProdutoNegociar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto a negociar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaptacaoClienteRepository.cls
public class CaptacaoClienteRepository {
    public List<Account> buscarContasPorDocumento(Set<String> documentos) {
        return [
            SELECT 
                Id,
                Owner.Name,
                Documento__c
            FROM 
                Account 
            WHERE 
                Documento__c IN: documentos
        ];
    }

    public List<DadoBancario__c> buscarDadosBancariosExistentes(Set<Id> setIdLead, Set<String> setCodAgencia, Set<String> setCodBanco, Set<String> setContaBancaria, Set<String> setDigitoBancario){
        return [
            SELECT
                Id,
                Agencia__c,
                Conta__c,
                DV__c,
                Lead__c,
                InstituicaoFinanceira__c
            FROM
                DadoBancario__c
            WHERE
                Agencia__c != null AND Agencia__c IN :setCodAgencia
            AND
                Conta__c != null AND Conta__c IN :setContaBancaria
            AND
                Lead__c != null AND Lead__c IN :setIdLead
            AND 
                DV__c != null AND DV__c IN :setDigitoBancario
            AND
                InstituicaoFinanceira__c != null AND InstituicaoFinanceira__c IN :setCodBanco
            WITH
                SYSTEM_MODE
            ORDER BY
                CreatedDate DESC
        ];
    }

    public List<InformcoesFinanceirasConta__c> buscarInformacoesFinanceirasContaExistentes(Set<Id> setIdConta, Set<String> setCodAgencia, Set<String> setCodBanco, Set<String> setContaBancaria, Set<String> setDigitoBancario){
        return [
            SELECT
                Id,
                Agencia__c,
                Conta__c,
                ContaRelacionada__c,
                DV__c,
                InstituicaoFinaneira__c
            FROM
                InformcoesFinanceirasConta__c
            WHERE
                Agencia__c != null AND Agencia__c IN :setCodAgencia
            AND
                Conta__c != null AND Conta__c IN :setContaBancaria
            AND
                ContaRelacionada__c != null AND ContaRelacionada__c IN :setIdConta
            AND 
                DV__c != null AND DV__c IN :setDigitoBancario
            AND
                InstituicaoFinaneira__c != null AND InstituicaoFinaneira__c IN :setCodBanco
            WITH
                SYSTEM_MODE
            ORDER BY
                CreatedDate DESC
        ];
    }

    public List<Lead> buscarLeadPorDocumentoEProdutoDiaAtual(String documentoFormatado, Id idProduto, Id idTipoRegistro) {
        return [
            SELECT 
                Id,
                Documento__c,
                ProdutoNegociar__c
            FROM 
                Lead 
            WHERE 
                Documento__c =: documentoFormatado AND
                ProdutoNegociar__c =: idProduto AND
                CreatedDate = TODAY
        ];
    }

    public Product2 buscarProdutoPorNome(String nomeProduto) {
        Map<String, String> produtosEuro17Credito = new Map<String, String>{
            'Financiamento de imóvel' => 'FINANCIAMENTO DE IMOVEIS',
            'Veículo pesado em garantia' => 'EMPRESTIMO C/ GAR. VEIC.PESADO',
            'Financiamento de veículo' => 'FINANCIAMENTO DE VEICULOS',
            'Veículo em garantia' => 'EMPRESTIMO C/GARANTIA VEICULOS',
            'Imóvel em garantia' => 'EMPRESTIMO C/ GARANTIA IMOVEIS'
        };

        nomeProduto = produtosEuro17Credito.get(nomeProduto);

        return [
            SELECT 
                Id,
                Name
            FROM 
                Product2 
            WHERE 
                Name =:nomeProduto
            LIMIT 1
        ];
    }
}