force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DadoBancario__c/DadoBancario__c.object-meta.xml
<CustomObject>
    <label>Dado bancário</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Dado bancário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados bancários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DadoBancario__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/DV__c.field-meta.xml
<CustomField>
    <fullName>DV__c</fullName>
    <label>DV</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/InstituicaoFinanceira__c.field-meta.xml
<CustomField>
    <fullName>InstituicaoFinanceira__c</fullName>
    <label>Instituição Financeira</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
                <label>001-Banco do Brasil S.A.</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003-Banco da Amazônia S.A.</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004-Banco do Nordeste do Brasil S.A.</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007-Banco Nacional de Desenvolvimento Econômico e Social - BNDES</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012-Banco Inbursa S.A.</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014-State Street Brasil S.A. - Banco Comercial</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017-BNY Mellon Banco S.A.</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021-BANESTES S.A. Banco do Estado do Espírito Santo</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024-Banco BANDEPE S.A.</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025-Banco Alfa S.A.</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029-Banco Itaú Consignado S.A.</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033-Banco Santander (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036-Banco Bradesco BBI S.A.</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037-Banco do Estado do Pará S.A.</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040-Banco Cargill S.A.</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041-Banco do Estado do Rio Grande do Sul S.A.</label>
            </value>
            <value>
                <fullName>047</fullName>
                <label>047-Banco do Estado de Sergipe S.A.</label>
            </value>
            <value>
                <fullName>062</fullName>
                <label>062-Hipercard Banco Múltiplo S.A.</label>
            </value>
            <value>
                <fullName>063</fullName>
                <label>063-Banco Bradescard S.A.</label>
            </value>
            <value>
                <fullName>065</fullName>
                <label>065-Banco Andbank (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>066</fullName>
                <label>066-Banco Morgan Stanley S.A.</label>
            </value>
            <value>
                <fullName>070</fullName>
                <label>070-BRB - Banco de Brasília S.A.</label>
            </value>
            <value>
                <fullName>074</fullName>
                <label>074-Banco J. Safra S.A.</label>
            </value>
            <value>
                <fullName>077</fullName>
                <label>077-Banco Inter S.A.</label>
            </value>
            <value>
                <fullName>082</fullName>
                <label>082-Banco Topázio S.A.</label>
            </value>
            <value>
                <fullName>083</fullName>
                <label>083-Banco da China Brasil S.A.</label>
            </value>
            <value>
                <fullName>084</fullName>
                <label>084-Sisprime do Brasil</label>
            </value>
            <value>
                <fullName>094</fullName>
                <label>094-Banco Finaxis S.A.</label>
            </value>
            <value>
                <fullName>095</fullName>
                <label>095-Travelex Banco de Câmbio S.A.</label>
            </value>
            <value>
                <fullName>096</fullName>
                <label>096-Banco B3 S.A.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DadoBancario__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Dados bancários</relationshipLabel>
    <relationshipName>DadosBancarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/InformcoesFinanceirasConta__c.object-meta.xml
<CustomObject>
    <label>Informações financeiras da conta</label>
    <nameField>
        <label>Informações financeiras da conta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações financeiras da conta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/ContaRelacionada__c.field-meta.xml
<CustomField>
    <fullName>ContaRelacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informações financeiras da conta</relationshipLabel>
    <relationshipName>InformacoesFinanceirasConta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informar CPF para pessoa física ou CNPJ pessoa jurídica</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/fields/InstituicaoFinaneira__c.field-meta.xml
<CustomField>
    <fullName>InstituicaoFinaneira__c</fullName>
    <label>Instituição Financeira</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
                <label>001-Banco do Brasil S.A.</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003-Banco da Amazônia S.A.</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004-Banco do Nordeste do Brasil S.A.</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007-Banco Nacional de Desenvolvimento Econômico e Social - BNDES</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012-Banco Inbursa S.A.</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014-State Street Brasil S.A. - Banco Comercial</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017-BNY Mellon Banco S.A.</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021-BANESTES S.A. Banco do Estado do Espírito Santo</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024-Banco BANDEPE S.A.</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025-Banco Alfa S.A.</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029-Banco Itaú Consignado S.A.</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033-Banco Santander (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036-Banco Bradesco BBI S.A.</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037-Banco do Estado do Pará S.A.</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040-Banco Cargill S.A.</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041-Banco do Estado do Rio Grande do Sul S.A.</label>
            </value>
            <value>
                <fullName>047</fullName>
                <label>047-Banco do Estado de Sergipe S.A.</label>
            </value>
            <value>
                <fullName>062</fullName>
                <label>062-Hipercard Banco Múltiplo S.A.</label>
            </value>
            <value>
                <fullName>063</fullName>
                <label>063-Banco Bradescard S.A.</label>
            </value>
            <value>
                <fullName>065</fullName>
                <label>065-Banco Andbank (Brasil) S.A.</label>
            </value>
            <value>
                <fullName>066</fullName>
                <label>066-Banco Morgan Stanley S.A.</label>
            </value>
            <value>
                <fullName>070</fullName>
                <label>070-BRB - Banco de Brasília S.A.</label>
            </value>
            <value>
                <fullName>074</fullName>
                <label>074-Banco J. Safra S.A.</label>
            </value>
            <value>
                <fullName>077</fullName>
                <label>077-Banco Inter S.A.</label>
            </value>
            <value>
                <fullName>082</fullName>
                <label>082-Banco Topázio S.A.</label>
            </value>
            <value>
                <fullName>083</fullName>
                <label>083-Banco da China Brasil S.A.</label>
            </value>
            <value>
                <fullName>084</fullName>
                <label>084-Sisprime do Brasil</label>
            </value>
            <value>
                <fullName>094</fullName>
                <label>094-Banco Finaxis S.A.</label>
            </value>
            <value>
                <fullName>095</fullName>
                <label>095-Travelex Banco de Câmbio S.A.</label>
            </value>
            <value>
                <fullName>096</fullName>
                <label>096-Banco B3 S.A.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformcoesFinanceirasConta__c/recordTypes/DadoBancario.recordType-meta.xml
<RecordType>
    <fullName>DadoBancario</fullName>
    <active>true</active>
    <description>Cadastro de dados bancários relacionadas à conta.</description>
    <label>Dado bancário</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informe o CPF para Pessoa Física ou CNPJ para Pessoa Jurídica.</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/ProdutosFinanceiros.recordType-meta.xml
<RecordType>
    <fullName>ProdutosFinanceiros</fullName>
    <active>true</active>
    <businessProcess>Securitizadora</businessProcess>
    <label>Produtos Financeiros</label>
</RecordType>

force-app/main/default/classes/CaptacaoClienteService.cls
public class CaptacaoClienteService {
    private CaptacaoClienteRepository repository = new CaptacaoClienteRepository();
    private CaptacaoCliente captacaoCliente = new CaptacaoCliente();

    //Executa criação de novo lead ou oportunidade
    public void criarLead(CaptacaoClienteSchema.LeadRequest leadRequest) {
        if(leadRequest.origem == 'Site Euro 17 Crédito') {
            verificarLeadComMesmoProdutoFinanceiro(leadRequest.documento, leadRequest.produtoInteresse);
        }

        //Busca possiveis contas já cadastradas com o CNPJ do lead a ser criado
        List<Account> contas = this.repository.buscarContasPorDocumento(new Set<String>{Format.documento(leadRequest.documento)});        
        this.captacaoCliente.criarLeadOportunidade(leadRequest, contas);
    }

    //Verifica se uma conta já existe
    public void validarContasExistente(List<Account> contas) {
        Set<String> documentos = new Set<String>();
        Set<String> documentosContasExistentes = new Set<String>();

        for(Account acc : contas){
            //TODO: FAZER TRATAMENTO PARA TRATAR CPF TBM
            documentos.add(Format.documento(acc.Documento__c));
        }

        for(Account contaExistente : this.repository.buscarContasPorDocumento(documentos)) {
            documentosContasExistentes.add(contaExistente.Documento__c);
        }
        
        this.captacaoCliente.validarContasExistentes(contas, documentosContasExistentes);
    }

    public void validarDadosBancariosExistentes(List<DadoBancario__c> listDadosBancarios){
        Map<String, DadoBancario__c> mapChaveCompostaDadoBancarioTransacao = new Map<String, DadoBancario__c>();
        Set<Id> setIdLead = new Set<Id>();
        Set<String> setCodAgencia = new Set<String>();
        Set<String> setCodBanco = new Set<String>();
        Set<String> setContaBancaria = new Set<String>();
        Set<String> setDigitoBancario = new Set<String>();
    
        for(DadoBancario__c dadoBancario : listDadosBancarios){
            String chaveComposta = dadoBancario.Lead__c + ' | ' + dadoBancario.InstituicaoFinanceira__c + ' | ' + dadoBancario.Agencia__c + ' | ' + dadoBancario.Conta__c + ' | ' + dadoBancario.DV__c;
            DadoBancario__c dadoBancarioTransacao = mapChaveCompostaDadoBancarioTransacao.get(chaveComposta);

            if(dadoBancarioTransacao != null)
                dadoBancario.addError('Já existe um registro de Dado bancário para este lead com as mesmas informações de instituição financeira, agência, conta e DV fornecidas nesta mesma transação.');
            else{
                mapChaveCompostaDadoBancarioTransacao.put(chaveComposta, dadoBancario);
                setIdLead.add(dadoBancario.Lead__c);
                setCodAgencia.add(dadoBancario.Agencia__c);
                setCodBanco.add(dadoBancario.InstituicaoFinanceira__c);
                setContaBancaria.add(dadoBancario.Conta__c);
                setDigitoBancario.add(dadoBancario.DV__c);
            }
        }

        if(!setIdLead.isEmpty()){         
            List<DadoBancario__c> listDadosBancariosExistentes = this.repository.buscarDadosBancariosExistentes(setIdLead, setCodAgencia, setCodBanco, setContaBancaria, setDigitoBancario);
            Map<String, DadoBancario__c> mapChaveCompostaDadoBancario = new Map<String, DadoBancario__c>();

            for(DadoBancario__c dadoBancarioExistente : listDadosBancariosExistentes)
                mapChaveCompostaDadoBancario.put(dadoBancarioExistente.Lead__c + ' | ' + dadoBancarioExistente.InstituicaoFinanceira__c + ' | ' + 
                    dadoBancarioExistente.Agencia__c + ' | ' + dadoBancarioExistente.Conta__c + ' | ' + dadoBancarioExistente.DV__c, dadoBancarioExistente);
    
            for(DadoBancario__c dadoBancario : listDadosBancarios){
                String chaveComposta = dadoBancario.Lead__c + ' | ' + dadoBancario.InstituicaoFinanceira__c + ' | ' + dadoBancario.Agencia__c + ' | ' + dadoBancario.Conta__c + ' | ' + dadoBancario.DV__c;
                DadoBancario__c dadoBancarioExistente = mapChaveCompostaDadoBancario.get(chaveComposta);

                if(dadoBancarioExistente != null && dadoBancarioExistente.Id != dadoBancario.Id)
                    dadoBancario.addError('Já existe um registro de Dado bancário para este lead com as mesmas informações de instituição financeira, agência, conta e DV fornecidas.');
            }
        }
    }

    public void validarInfoFinanceirasContaExistentes(List<InformcoesFinanceirasConta__c> listInfoFinanceirasConta){
        Id dadoBancarioRecTypeId = Schema.SObjectType.InformcoesFinanceirasConta__c.getRecordTypeInfosByDeveloperName().get('DadoBancario').getRecordTypeId();
        List<InformcoesFinanceirasConta__c> listInfoFinaceirasContaDB = new List<InformcoesFinanceirasConta__c>();
        Map<String, InformcoesFinanceirasConta__c> mapChaveCompostaInfoFinanceiraTransacao = new Map<String, InformcoesFinanceirasConta__c>();
        Set<Id> setIdConta = new Set<Id>();
        Set<String> setCodAgencia = new Set<String>();
        Set<String> setCodBanco = new Set<String>();
        Set<String> setContaBancaria = new Set<String>();
        Set<String> setDigitoBancario = new Set<String>();
    
        for(InformcoesFinanceirasConta__c infoFinanceira : listInfoFinanceirasConta){
            if(infoFinanceira.RecordTypeId == dadoBancarioRecTypeId){
                String chaveComposta = infoFinanceira.ContaRelacionada__c + ' | ' + infoFinanceira.InstituicaoFinaneira__c + ' | ' + infoFinanceira.Agencia__c + ' | ' + infoFinanceira.Conta__c + ' | ' + infoFinanceira.DV__c;
                InformcoesFinanceirasConta__c infoFinanceiraTransacao = mapChaveCompostaInfoFinanceiraTransacao.get(chaveComposta);

                if(infoFinanceiraTransacao != null)
                    infoFinanceira.addError('Já existe um registro de Dado bancário para este cliente com as mesmas informações de instituição financeira, agência, conta e DV fornecidas nesta mesma transação.');
                else{
                    listInfoFinaceirasContaDB.add(infoFinanceira);
                    mapChaveCompostaInfoFinanceiraTransacao.put(chaveComposta, infoFinanceira);
                    setIdConta.add(infoFinanceira.ContaRelacionada__c);
                    setCodAgencia.add(infoFinanceira.Agencia__c);
                    setCodBanco.add(infoFinanceira.InstituicaoFinaneira__c);
                    setContaBancaria.add(infoFinanceira.Conta__c);
                    setDigitoBancario.add(infoFinanceira.DV__c);
                }
            }
        }

        if(!setIdConta.isEmpty()){         
            List<InformcoesFinanceirasConta__c> listInfoFinanceirasContaExistentes = this.repository.buscarInformacoesFinanceirasContaExistentes(setIdConta, setCodAgencia, setCodBanco, setContaBancaria, setDigitoBancario);
            Map<String, InformcoesFinanceirasConta__c> mapChaveCompostaInfoFinanceira = new Map<String, InformcoesFinanceirasConta__c>();

            for(InformcoesFinanceirasConta__c infoFinanceiraExistente : listInfoFinanceirasContaExistentes)
                mapChaveCompostaInfoFinanceira.put(infoFinanceiraExistente.ContaRelacionada__c + ' | ' + infoFinanceiraExistente.InstituicaoFinaneira__c + ' | ' + 
                    infoFinanceiraExistente.Agencia__c + ' | ' + infoFinanceiraExistente.Conta__c + ' | ' + infoFinanceiraExistente.DV__c, infoFinanceiraExistente);
    
            for(InformcoesFinanceirasConta__c infoFinanceiraDB : listInfoFinaceirasContaDB){
                String chaveComposta = infoFinanceiraDB.ContaRelacionada__c + ' | ' + infoFinanceiraDB.InstituicaoFinaneira__c + ' | ' + infoFinanceiraDB.Agencia__c + ' | ' + infoFinanceiraDB.Conta__c + ' | ' + infoFinanceiraDB.DV__c;
                InformcoesFinanceirasConta__c infoFinanceiraExistente = mapChaveCompostaInfoFinanceira.get(chaveComposta);

                if(infoFinanceiraExistente != null && infoFinanceiraExistente.Id != infoFinanceiraDB.Id)
                    infoFinanceiraDB.addError('Já existe um registro de Dado bancário para este cliente com as mesmas informações de instituição financeira, agência, conta e DV fornecidas.');
            }
        }
    }

    public void formatarDocumentoConta(List<Account> contas){
        for(Account conta : contas){
            if(conta.Documento__c != null && (conta.Documento__c.length() == 18 || conta.Documento__c.length() == 14 || conta.Documento__c.length() == 11)){
                conta.Documento__c = Format.documento(conta.Documento__c);
            } else {
                conta.addError('Para o campo documento, digitar somente um CPF ou CNPJ válido. Não é possível salvar o campo somente com letras ou com uma sequência de mesmo número. Ex: 111111111-11.');
            }
        }
    }

    public void formatarDocumentoLead(List<Lead> leads){
        Set<String> origemLead = new Set<String>{'Site Euro Securitizadora'};
        for(Lead lead : leads){
            if(lead.Documento__c != null ){
                if(!origemLead.contains(lead.LeadSource) && (lead.Documento__c.length() == 18 || lead.Documento__c.length() == 14 || lead.Documento__c.length() == 11)){
                    lead.Documento__c = Format.documento(lead.Documento__c);
                }else if(origemLead.contains(lead.LeadSource)){
                    lead.Documento__c = Format.documento(lead.Documento__c);
                } else {
                    lead.addError('Para o campo documento, digitar somente um CPF ou CNPJ válido. Não é possível salvar o campo somente com letras ou com uma sequência de mesmo número. Ex: 111111111-11.');
                }
            }
        }
    }

    public CaptacaoClienteSchema.LeadConversionResponse converterLead(CaptacaoClienteSchema.LeadConversionRequest leadRequest) {
        Database.LeadConvert leadConvert = new Database.LeadConvert();
        List<Account> contaExistente = this.repository.buscarContasPorDocumento(new Set<String>{leadRequest.documentoLead});
                    
        return captacaoCliente.converterLead(leadRequest, contaExistente);
    }

    public void verificarLeadComMesmoProdutoFinanceiro(String documento, String nomeProduto) {
        String documentoFormatado = Format.documento(documento);
        Id idProduto = repository.buscarProdutoPorNome(nomeProduto).Id;
        Id idTipoRegistro = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('ProdutosFinanceiros').getRecordTypeId();

        List<Lead> leads = this.repository.buscarLeadPorDocumentoEProdutoDiaAtual(documentoFormatado, idProduto, idTipoRegistro);

        if(leads.size() > 0) {
            throw new CaptacaoClienteServiceException('Existe uma solicitação em andamento para o produto solicitado. Em breve retornaremos o contato.');
        }
    }

    public class CaptacaoClienteServiceException extends Exception {}
}