force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TipoPessoa__c.field-meta.xml
<CustomField>
    <fullName>TipoPessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pessoa Física</fullName>
            </value>
            <value>
                <fullName>Pessoa Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <label>Número do contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/DataFimContrato__c.field-meta.xml
<CustomField>
    <fullName>DataFimContrato__c</fullName>
    <label>Data fim do contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/DataInicioContrato__c.field-meta.xml
<CustomField>
    <fullName>DataInicioContrato__c</fullName>
    <label>Data início do contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Periodo__c.field-meta.xml
<CustomField>
    <fullName>Periodo__c</fullName>
    <label>Periodo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Mensal</fullName>
            </value>
            <value>
                <fullName>PMT</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/PrazoContrato__c.field-meta.xml
<CustomField>
    <fullName>PrazoContrato__c</fullName>
    <label>Prazo do contrato</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Serie__c.field-meta.xml
<CustomField>
    <fullName>Serie__c</fullName>
    <label>Série</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ª</fullName>
            </value>
            <value>
                <fullName>2ª</fullName>
            </value>
            <value>
                <fullName>3ª</fullName>
            </value>
            <value>
                <fullName>4ª</fullName>
            </value>
            <value>
                <fullName>5ª</fullName>
            </value>
            <value>
                <fullName>6ª</fullName>
            </value>
            <value>
                <fullName>7ª</fullName>
            </value>
            <value>
                <fullName>8ª</fullName>
            </value>
            <value>
                <fullName>9ª</fullName>
            </value>
            <value>
                <fullName>10ª</fullName>
            </value>
            <value>
                <fullName>11ª</fullName>
            </value>
            <value>
                <fullName>12ª</fullName>
            </value>
            <value>
                <fullName>13ª</fullName>
            </value>
            <value>
                <fullName>14ª</fullName>
            </value>
            <value>
                <fullName>15ª</fullName>
            </value>
            <value>
                <fullName>16ª</fullName>
            </value>
            <value>
                <fullName>17ª</fullName>
            </value>
            <value>
                <fullName>18ª</fullName>
            </value>
            <value>
                <fullName>19ª</fullName>
            </value>
            <value>
                <fullName>20ª</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando elaboração</fullName>
            </value>
            <value>
                <fullName>Elaboração de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato Enviado</fullName>
            </value>
            <value>
                <fullName>Declinado</fullName>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Taxa__c.field-meta.xml
<CustomField>
    <fullName>Taxa__c</fullName>
    <label>Taxa</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/TipoContrato__c.field-meta.xml
<CustomField>
    <fullName>TipoContrato__c</fullName>
    <label>Tipo de contrato</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Novo aporte</fullName>
            </value>
            <value>
                <fullName>Empréstimo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/ValorContrato__c.field-meta.xml
<CustomField>
    <fullName>ValorContrato__c</fullName>
    <label>Valor do contrato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato__c/recordTypes/Investimentos.recordType-meta.xml
<RecordType>
    <fullName>Investimentos</fullName>
    <active>true</active>
    <label>Investimentos</label>
</RecordType>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/InformacoesFinanceirasOportunidade__c.object-meta.xml
<CustomObject>
    <label>Informações financeiras da oportunidade</label>
    <nameField>
        <displayFormat>IFO-{0000}</displayFormat>
        <label>Informações financeiras da oportunidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações financeiras da oportunidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Informações financeiras da oportunidade</relationshipLabel>
    <relationshipName>InformacoesFinanceirasOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Informações financeiras da oportunidade</relationshipLabel>
    <relationshipName>InformacoesFinanceirasOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/fields/Utilizado__c.field-meta.xml
<CustomField>
    <fullName>Utilizado__c</fullName>
    <label>% Utilizado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InformacoesFinanceirasOportunidade__c/recordTypes/Garantia.recordType-meta.xml
<RecordType>
    <fullName>Garantia</fullName>
    <active>true</active>
    <description>Para relacionar uma debênture em garantia no caso de empréstimo com investimento em garantia</description>
    <label>Garantia</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DataAporte__c.field-meta.xml
<CustomField>
    <fullName>DataAporte__c</fullName>
    <label>Data do Aporte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DataFimContrato__c.field-meta.xml
<CustomField>
    <fullName>DataFimContrato__c</fullName>
    <label>Data fim do contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DataInicioContrato__c.field-meta.xml
<CustomField>
    <fullName>DataInicioContrato__c</fullName>
    <label>Data de início do contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>Account.Documento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Periodo__c.field-meta.xml
<CustomField>
    <fullName>Periodo__c</fullName>
    <label>Período</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensal</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>PMT</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrazoOperacao__c.field-meta.xml
<CustomField>
    <fullName>PrazoOperacao__c</fullName>
    <inlineHelpText>Informar prazo em meses</inlineHelpText>
    <label>Prazo da Operação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Taxa__c.field-meta.xml
<CustomField>
    <fullName>Taxa__c</fullName>
    <label>Taxa</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ValorOportunidade__c</fullName>
    <label>Valor da Oportunidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Investimentos.recordType-meta.xml
<RecordType>
    <fullName>Investimentos</fullName>
    <active>true</active>
    <businessProcess>Oportunidades Captação e Investimento</businessProcess>
    <label>Investimentos</label>
</RecordType>

force-app/main/default/classes/ContratosGarantiaTest.cls
@IsTest
private class ContratosGarantiaTest {
    
    @TestSetup
    static void makeData(){
        Account conta = new Account(
            Documento__c = '27115620008',
            Email__c = 'conta@teste.com',
            FirstName = 'Conta',
            LastName = 'Teste',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ContaPessoal').getRecordTypeId(),
            TipoPessoa__c = 'Pessoa Física'
        );
        insert conta;

        Opportunity opp = new Opportunity(
            AccountId = conta.Id,
            CloseDate = System.today().addDays(1),
            DataAporte__c = System.today(),
            DataFimContrato__c = System.today().addYears(7),
            Name = 'Teste Invest',
            Periodo__c = 'Mensal',
            PrazoOperacao__c = 84,
            Quantidade__c = 100,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Investimentos').getRecordTypeId(),
            StageName = 'Elaboração de Contrato',
            Taxa__c = 1.3,
            Type = 'Novo aporte',
            ValorOportunidade__c = 100000
        );
        insert opp;

        Contrato__c contrato = new Contrato__c(
            Conta__c = conta.Id,
            DataFimContrato__c = System.today().addYears(7),
            DataInicioContrato__c = System.today(),
            Oportunidade__c = opp.id,
            Periodo__c = 'Mensal',
            PrazoContrato__c = 84,
            RecordTypeId = Schema.SObjectType.Contrato__c.getRecordTypeInfosByDeveloperName().get('Investimentos').getRecordTypeId(),
            Serie__c = '13ª',
            Status__c = 'Aguardando elaboração',
            Taxa__c = 1.3,
            TipoContrato__c = 'Novo Aporte',
            ValorContrato__c = 100000
        );
        insert contrato;

        InformacoesFinanceirasOportunidade__c infoOpp = new InformacoesFinanceirasOportunidade__c(
            //Contrato__c = contrato.Id,
            Oportunidade__c = opp.Id,
            RecordTypeId = Schema.SObjectType.InformacoesFinanceirasOportunidade__c.getRecordTypeInfosByDeveloperName().get('Garantia').getRecordTypeId(),
            Utilizado__c = 10
        );
        insert infoOpp;
    }

    @IsTest
    static void retornarContratosGarantia(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Account.Documento__c = '271.156.200-08' LIMIT 1];
        List<InformacoesFinanceirasOportunidade__c> lstGarantias = ContratosGarantiaController.buscarContratosInvestimentos(opp.Id);

        Assert.areEqual(1, lstGarantias.size());
    }

}