force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/TipoPessoa__c.field-meta.xml
<CustomField>
    <fullName>TipoPessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pessoa Física</fullName>
            </value>
            <value>
                <fullName>Pessoa Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Código Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro criado para cadastrar parceiros (PF e PJ)</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Produtos.recordType-meta.xml
<RecordType>
    <fullName>Produtos</fullName>
    <active>true</active>
    <label>Produtos</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <label>Código Filial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; IdFilial__c, IdFilial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegracaoClienteParceiroInvocableTest.cls
@IsTest
private class IntegracaoClienteParceiroInvocableTest {

    @TestSetup
    static void makeData(){
        // Setup test data
        Account testAccount = new Account(
            FirstName = 'Test',
            LastName = 'Pessoa Física',
            Documento__c = '441.287.810-45', 
            TipoPessoa__c = 'Pessoa Física',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ContaPessoal').getRecordTypeId()
        );
        insert testAccount;

        Product2 testProduct = new Product2(Name = 'Euro Prime Securitizadora');
        insert testProduct;

        PricebookEntry pbEntry = new PricebookEntry(
            IsActive = true,
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = testProduct.Id,
            UnitPrice = 1000
        );
        insert pbEntry;

        Filial__c filial = new Filial__c(
            CodigoEmpresa__c = '01',
            CodigoFilial__c = '01001' 
        );
        insert filial;

        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Grupo Euro 17'];

        User testOwner = new User(
            FirstName = 'Test',
            LastName = 'Account',
            UserName = 'username@grupoeuro17.dev',
            Email = 'username@grupoeuro17.com',
            TimeZoneSidKey = 'America/Sao_Paulo',
            LocaleSidKey = 'pt_BR',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'pt_BR',
            Alias = 'username',
            ProfileId = testProfile.Id,
            Documento__c = '94327064009'
        );
        insert testOwner;

        CodigoProtheus__c codigoProtheus = new CodigoProtheus__c(
            Ativo__c = true,
            Codigo__c = 'TESTE 01',
            Filial__c = filial.Id,
            IdExterno__c = filial.CodigoFilial__c + '|' + 'TESTE 01',
            RecordTypeId = Schema.SObjectType.CodigoProtheus__c.getRecordTypeInfosByDeveloperName().get('Produtos').getRecordTypeId(),
            Produto__c = testProduct.Id
        );
        insert codigoProtheus;
    }

    @IsTest
    static void testIntegrarParceiroProtheus(){
        Account testAccount = [SELECT Id FROM Account WHERE Documento__c = '441.287.810-45' LIMIT 1];
        
        IntegracaoClienteParceiroInvocable.Request requestObj = new IntegracaoClienteParceiroInvocable.Request();
        requestObj.idConta = testAccount.Id;
        
        Test.startTest();
        IntegracaoClienteParceiroInvocable.integrarClienteParceiroProtheus(new List<IntegracaoClienteParceiroInvocable.Request>{requestObj});
        Bdrs.Callout.setTestResponse('{"access_token": "tokenstring"}', 201, 'Created'); 
        Bdrs.WorkControl.processWorks();
        Test.stopTest();
        
        List<CodigoProtheus__c> createdCodes = [SELECT Id, Codigo__c, RecordType.Name FROM CodigoProtheus__c WHERE Conta__c =: testAccount.Id];
        Assert.areEqual(1, createdCodes.size(), 'Expected a new WorkControl__c record');
        Assert.areEqual('441287', createdCodes[0].Codigo__c);
        Assert.areEqual('Parceiro', createdCodes[0].RecordType.Name);
    }

}