force-app/main/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <externalId>true</externalId>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/CodigoProtheus__c.object-meta.xml
<CustomObject>
    <label>Código Protheus</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Código Protheus</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Códigos Protheus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CodigoProtheus__c/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <referenceTo>Filial__c</referenceTo>
    <relationshipLabel>Códigos Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Produto: CodigoFilial + CodigoProduto
Conta: UnidadeNegocio + Empresa + 9 DigitosDocumento
Parceiro: Código da Empresa | 6 Dígitos do Documento
Representante: Código da Filial | Documento</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Código Protheus</relationshipLabel>
    <relationshipName>CodigosProtheus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/CodigoProtheus__c/recordTypes/Produtos.recordType-meta.xml
<RecordType>
    <fullName>Produtos</fullName>
    <active>true</active>
    <label>Produtos</label>
</RecordType>

force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filial__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>Account.Documento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrazoOperacao__c.field-meta.xml
<CustomField>
    <fullName>PrazoOperacao__c</fullName>
    <inlineHelpText>Informar prazo em meses</inlineHelpText>
    <label>Prazo da Operação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Taxa__c.field-meta.xml
<CustomField>
    <fullName>Taxa__c</fullName>
    <label>Taxa</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ValorOportunidade__c</fullName>
    <label>Valor da Oportunidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Investimentos.recordType-meta.xml
<RecordType>
    <fullName>Investimentos</fullName>
    <active>true</active>
    <businessProcess>Oportunidades Captação e Investimento</businessProcess>
    <label>Investimentos</label>
</RecordType>

force-app/main/default/objects/Product2/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoProtheus__c.field-meta.xml
<CustomField>
    <fullName>CodigoProtheus__c</fullName>
    <label>Código Protheus</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; IdFilial__c, IdFilial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretor</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Gestor(a)</fullName>
            </value>
            <value>
                <fullName>Analista</fullName>
            </value>
            <value>
                <fullName>Analista SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NegociacaoTest.cls
@IsTest
private class NegociacaoTest {

    @TestSetup
    static void makeData(){
        User gerenciador = [SELECT Id FROM User WHERE IsActive = true AND ManagerId != null AND Profile.Name = 'Grupo Euro 17' LIMIT 1];
        User userAtual = new User(Funcao__c = 'Vice presidencia', Id = UserInfo.getUserId(), ManagerId = gerenciador.Id);

        update userAtual;
    }

    @IsTest
    static void testCriarFilial() {
        // Criar dados de teste
        List<NegociacaoSchema.Filial> filialRequest = new List<NegociacaoSchema.Filial>{};

        NegociacaoSchema.Filial teste1 = new NegociacaoSchema.Filial();
        NegociacaoSchema.Filial teste2 = new NegociacaoSchema.Filial();

        teste1.cnpj = '12345678901234';
        teste1.filial = 'teste';
        teste1.razaoSocial = 'teste';
        teste1.codigoEmpresa = '123';
        teste1.codigoFilial = '123';
        teste1.status = true;

        teste2.cnpj = '22345678901234';
        teste2.filial = 'teste';
        teste2.razaoSocial = 'teste';
        teste2.codigoEmpresa = '124';
        teste2.codigoFilial = '124';
        teste2.status = true;

        filialRequest.add(teste1);
        filialRequest.add(teste2);

        NegociacaoSchema.FilialRequest filial = new NegociacaoSchema.FilialRequest();
        filial.filialFields = filialRequest;

        Test.startTest();
        NegociacaoService negocicao = new NegociacaoService();
        negocicao.criarFilial(filial);
        Test.stopTest();
        
        // Realizar asserções ou consultas para verificar os resultados
        List<Filial__c> filiaisCriadas = [SELECT Id, CNPJ__c FROM Filial__c WHERE CNPJ__c IN ('12.345.678/9012-34', '22.345.678/9012-34')];
        Assert.areEqual(2, filiaisCriadas.size());
    }

    @IsTest
    static void testCriarProduto() {
        // Criar dados de teste
        List<NegociacaoSchema.Produto> produtoRequest = new List<NegociacaoSchema.Produto>{};

        List<NegociacaoSchema.Filial> filialRequest = new List<NegociacaoSchema.Filial>{};

        NegociacaoSchema.Filial teste1 = new NegociacaoSchema.Filial();
        NegociacaoSchema.Filial teste2 = new NegociacaoSchema.Filial();

        teste1.cnpj = '12345678901234';
        teste1.filial = 'teste';
        teste1.razaoSocial = 'teste';
        teste1.codigoEmpresa = '123';
        teste1.codigoFilial = '123';
        teste1.status = true;

        teste2.cnpj = '22345678901234';
        teste2.filial = 'teste';
        teste2.razaoSocial = 'teste';
        teste2.codigoEmpresa = '124';
        teste2.codigoFilial = '124';
        teste2.status = true;

        filialRequest.add(teste1);
        filialRequest.add(teste2);

        Set<Integer> filiaisSet = new Set<Integer>{124, 123};

        NegociacaoSchema.Produto prod1 = new NegociacaoSchema.Produto();
        NegociacaoSchema.Produto prod2 = new NegociacaoSchema.Produto();

        prod1.codigoProduto = '123';
        prod1.nomeProduto = 'teste';
        prod1.statusProduto = true;
        prod1.descricaoProduto = 'teste';
        prod1.filialProduto = '123';
        prod1.filiais = new List<NegociacaoSchema.Filial>();
        prod1.filiais.add(teste1);

        prod2.codigoProduto = '122';
        prod2.nomeProduto = 'teste2';
        prod2.statusProduto = true;
        prod2.descricaoProduto = 'teste';
        prod2.filialProduto = '123';
        prod2.filiais = new List<NegociacaoSchema.Filial>();
        prod2.filiais.add(teste2);

        produtoRequest.add(prod1);
        produtoRequest.add(prod2);
        
        NegociacaoSchema.ProdutoRequest produto = new NegociacaoSchema.ProdutoRequest();
        produto.produtos = produtoRequest;
        
        // Chamar o método de criação de produto
        Test.startTest();
        Negociacao negociacaoInstance = new Negociacao();
        NegociacaoService service = new NegociacaoService();
        negociacaoInstance.criarFilial(filialRequest);
        service.criarProduto(produto);
        Test.stopTest();
        
        // Realizar asserções ou consultas para verificar os resultados
        List<CodigoProtheus__C> codigosProtheusCriados = [SELECT Id, IdExterno__c FROM CodigoProtheus__C];
        Assert.areEqual(2, codigosProtheusCriados.size());
    }

    @IsTest
    static void aprovarEtapasGerenteGeral(){
        User usuarioAtual = new User(
            Funcao__c = 'Gerente geral',
            Id = UserInfo.getUserId()
        );

        update usuarioAtual;

        Account conta = new Account(
            Documento__c = '67634718076',
            FirstName = 'Maria',
            LastName = 'Teste',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ContaPessoal').getRecordTypeId()
        );
        insert conta;

        Product2 produto = new Product2(
            IsActive = true,
            Name = 'EURO PRIME SECURITIZADORA'
        );
        insert produto;

        Opportunity opp = new Opportunity(
            AccountId = conta.Id,
            CloseDate = System.today().addDays(1),
            Name = 'Maria Teste',
            PrazoOperacao__c = 84,
            Produto__c = produto.Id,
            Quantidade__c = 200,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Investimentos').getRecordTypeId(),
            StageName = 'Pendente',
            Taxa__c = 1.7,
            Type = 'Novo aporte',
            ValorOportunidade__c = 200000
        );
        insert opp;

        List<Approval.ProcessWorkitemRequest> lstApprovalReq = new List<Approval.ProcessWorkitemRequest>();
        List<ProcessInstanceWorkitem> listItensPendentes = new NegociacaoRepository().buscarItensPendentesAprovacao(new Set<Id> { opp.Id });

        for(ProcessInstanceWorkitem item : listItensPendentes){
            Approval.ProcessWorkitemRequest approvalReq = new Approval.ProcessWorkitemRequest();
            approvalReq.setWorkItemId(item.Id);
            approvalReq.setAction('Approve');
            approvalReq.setComments('Aprovado com sucesso.');
            lstApprovalReq.add(approvalReq);
        }

        Test.startTest();
            Approval.process(lstApprovalReq);
            String setOppIdsString = JSON.serialize(new Set<Id>{ opp.Id });
            String processResult = new AprovacaoProcessosWorkRun().process(setOppIdsString);
            String processResponse = new AprovacaoProcessosWorkRun().processResponse(setOppIdsString, processResult);
        Test.stopTest();

        List<ProcessInstanceStep> lstEtapasProcesso = [SELECT Id, Comments, CreatedDate, StepStatus FROM ProcessInstanceStep WHERE ProcessInstance.TargetObjectId =: opp.Id AND StepStatus != 'Started' ORDER BY CreatedDate DESC];
        Opportunity oppAtualizada = [SELECT Id, StageName FROM Opportunity WHERE Id =: opp.Id LIMIT 1];

        Assert.areEqual('Etapas do Processo de aprovação atualizadas com sucesso.', processResponse);
        Assert.areEqual('Aprovado com sucesso.', lstEtapasProcesso[0].Comments);
        Assert.areEqual('Approved', lstEtapasProcesso[0].StepStatus);
        Assert.areEqual('Validando Taxa/Prazo', oppAtualizada.StageName);
    }

    @IsTest
    static void aprovarEtapasVicePresidencia(){
        Account conta = new Account(
            Documento__c = '67634718076',
            FirstName = 'Maria',
            LastName = 'Teste',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ContaPessoal').getRecordTypeId()
        );
        insert conta;

        Product2 produto = new Product2(
            IsActive = true,
            Name = 'EURO PRIME SECURITIZADORA'
        );
        insert produto;

        Opportunity opp = new Opportunity(
            AccountId = conta.Id,
            CloseDate = System.today().addDays(1),
            Name = 'Maria Teste',
            PrazoOperacao__c = 84,
            Produto__c = produto.Id,
            Quantidade__c = 200,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Investimentos').getRecordTypeId(),
            StageName = 'Pendente',
            Taxa__c = 1.7,
            Type = 'Novo aporte',
            ValorOportunidade__c = 200000
        );
        insert opp;

        List<ProcessInstanceWorkItem> listItensPendentes = new NegociacaoRepository().buscarItensPendentesAprovacao(new Set<Id> { opp.Id });

        Approval.ProcessWorkitemRequest approvalReq = new Approval.ProcessWorkitemRequest();
        approvalReq.setWorkItemId(listItensPendentes[0].Id);
        approvalReq.setAction('Approve');
        approvalReq.setComments('Aprovado com sucesso pela VP.');
        Approval.process(approvalReq);

        Test.startTest();
            String setOppIdsString = JSON.serialize(new Set<Id>{ opp.Id });
            String processResult = new AprovacaoProcessosWorkRun().process(setOppIdsString);
            String processResponse = new AprovacaoProcessosWorkRun().processResponse(setOppIdsString, processResult);
        Test.stopTest();

        List<ProcessInstanceStep> lstEtapasProcesso = [SELECT Id, Comments, CreatedDate, StepStatus FROM ProcessInstanceStep WHERE ProcessInstance.TargetObjectId =: opp.Id AND StepStatus != 'Started' ORDER BY Id DESC];
        Opportunity oppAtualizada = [SELECT Id, StageName FROM Opportunity WHERE Id =: opp.Id LIMIT 1];

        Assert.areEqual('Etapas do Processo de aprovação atualizadas com sucesso.', processResponse);
        Assert.areEqual('Aprovado automaticamente pela VP.', lstEtapasProcesso[0].Comments);
        Assert.areEqual('Approved', lstEtapasProcesso[0].StepStatus);
        Assert.areEqual('Taxa/Prazo Aprovada', oppAtualizada.StageName);
    }

    @IsTest
    static void excecaoAprovarEtapasProcesso(){
        List<Approval.ProcessSubmitRequest> listApprovalSubmitRequest = new List<Approval.ProcessSubmitRequest>();
        List<Approval.ProcessWorkitemRequest> lstItensInvalidos = new List<Approval.ProcessWorkItemRequest>();
        Approval.ProcessWorkitemRequest request = new Approval.ProcessWorkitemRequest();
        request.setWorkItemId(UserInfo.getUserId());
        request.setAction('Approve');
        request.setComments('Aprovado automaticamente pela VP.');

        lstItensInvalidos.add(request);

        List<Opportunity> listOpportunity = new List<Opportunity>();
        List<Id> listOpportunityIdsInvalidos = new List<Id> { UserInfo.getUserId() };

        try{
            String result = new Negociacao().aprovarItensPendentes(lstItensInvalidos, listApprovalSubmitRequest, listOpportunityIdsInvalidos, listOpportunity);
        } catch(Exception e){
            Assert.isTrue(e.getMessage().contains('Erro ao avançar etapas do Processo de aprovação'));
        }
    }

}