force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DataHoraIntegracaoProtheus__c.field-meta.xml
<CustomField>
    <fullName>DataHoraIntegracaoProtheus__c</fullName>
    <description>Campo de controle para registrar os horários dos envios de Oportunidade ganha para o Protheus.</description>
    <label>Data/hora integração Protheus</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusProtheus__c.field-meta.xml
<CustomField>
    <fullName>StatusProtheus__c</fullName>
    <defaultValue>&apos;Não integrada&apos;</defaultValue>
    <description>Campo criado para controlar quando uma oportunidade é integrada no Protheus.</description>
    <label>Status Protheus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não integrada</fullName>
            </value>
            <value>
                <fullName>Em processamento</fullName>
            </value>
            <value>
                <fullName>Em reprocessamento</fullName>
            </value>
            <value>
                <fullName>Reprocessada</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Investimentos.recordType-meta.xml
<RecordType>
    <fullName>Investimentos</fullName>
    <active>true</active>
    <businessProcess>Oportunidades Captação e Investimento</businessProcess>
    <label>Investimentos</label>
</RecordType>

force-app/main/default/objects/SimulacaoCredito__c/SimulacaoCredito__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar as simulações retornadas pelo FlowFinance durante o cálculo de parcelas.</description>
    <label>Simulação de crédito</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulações de crédito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SimulacaoCredito__c/fields/Periodicidade__c.field-meta.xml
<CustomField>
    <fullName>Periodicidade__c</fullName>
    <label>Periodicidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>MONTHLY</fullName>
                <label>Mensal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SimulacaoCredito__c/fields/TipoIOF__c.field-meta.xml
<CustomField>
    <fullName>TipoIOF__c</fullName>
    <label>Tipo de IOF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BUSINESS</fullName>
                <label>PJ</label>
            </value>
            <value>
                <fullName>BUSINESS_SIMPLE</fullName>
                <label>PJ Simples</label>
            </value>
            <value>
                <fullName>ZERO</fullName>
                <label>Zerado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SimulacaoParcela__c/SimulacaoParcela__c.object-meta.xml
<CustomObject>
    <description>Objeto filho de Simulação de crédito, onde as parcelas serão armazenadas como registros contendo valores de juros e amortização de cada uma.</description>
    <label>Simulação de parcela</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulações de parcela</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SimulacaoParcela__c/fields/SimulacaoCredito__c.field-meta.xml
<CustomField>
    <fullName>SimulacaoCredito__c</fullName>
    <label>Simulação de crédito</label>
    <referenceTo>SimulacaoCredito__c</referenceTo>
    <relationshipLabel>Simulações de parcela</relationshipLabel>
    <relationshipName>SimulacoesParcela</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FormalizacaoService.cls
public without sharing class FormalizacaoService {
    
    private Formalizacao formalizacao = new Formalizacao();
    private FormalizacaoFactory factory = new FormalizacaoFactory();
    private FormalizacaoRepository repository = new FormalizacaoRepository();

    public void integrarOportunidadeGanhaProtheus(List<Opportunity> listOpportunityNew, Map<Id, Opportunity> mapOpportunityOld){
        Integer countDML = 0;
        List<Opportunity> listOportunidadesAtualizadas = new List<Opportunity>();
        Set<String> setUnidadesNegocioProtheus = new Set<String>{ 'Investimentos', 'Produtos financeiros', 'Produtos financeiros - Veículos' };

        for(Opportunity oportunidade : listOpportunityNew){
            Opportunity oportunidadeOld = mapOpportunityOld.get(oportunidade.Id);

            if(countDML < 51){
                if(setUnidadesNegocioProtheus.contains(oportunidade.UnidadeNegocio__c) && (oportunidade.IsWon && oportunidade.StageName != oportunidadeOld.StageName) || (oportunidade.StatusProtheus__c == 'Reprocessada' && oportunidade.DataHoraIntegracaoProtheus__c != oportunidadeOld.DataHoraIntegracaoProtheus__c)){
                    Bdrs.WorkControl.createOutboundWork(ProtheusOportunidadeGanhaWorkRun.class, JSON.serialize(oportunidade.Id), new Map<String, Object> {
                        'Priority__c' => 0 });
                    Bdrs.WorkControl.save();

                    Opportunity oportunidadeAtualizada = new Opportunity(Id = oportunidade.Id, StatusProtheus__c = 'Em processamento');
                    listOportunidadesAtualizadas.add(oportunidadeAtualizada);
                    countDML++;
                }
            } else
                break;

            update listOportunidadesAtualizadas;
        }
    }

    public String retornarEmailContaLead(Id recordId){
        Id accountId = recordId?.getSObjectType().getDescribe().getName() == 'Account' ? recordId : null;
        Id leadId = accountId == null ? recordId : null;
        String enderecoEmail;

        if(accountId != null)
            enderecoEmail = this.repository.buscarContaPorId(accountId).Email__c;
        else if(leadId != null)
            enderecoEmail = this.repository.buscarLeadPorId(leadId).Email;

        return enderecoEmail;    
    }

    public EmailTemplate retornarTemplateEmailExtrato(String numeroContrato, String urlDownloadContrato){
        EmailTemplate template = this.repository.buscarTemplateEmailPorNome('Extrato')[0];
        String userName = UserInfo.getName();
        this.factory.construirObjHtmlBody(template, numeroContrato, urlDownloadContrato, userName);

        return template;
    }

    public EmailTemplate retornarTemplateEmailSimulacaoCredito(FormalizacaoSchema.SimularParcelasLwcRequest objRequest, FormalizacaoSchema.SimularParcelasResponse objResponse){
        EmailTemplate template = this.repository.buscarTemplateEmailPorNome('Simulação de crédito')[0];
        String userName = UserInfo.getName();
        this.factory.construirObjHtmlBody(template, objRequest, objResponse, userName);

        return template;
    }

    public List<FormalizacaoSchema.PicklistField> retornarValoresPicklistSimulacao(){
        DescribeSObjectResult objResult = Schema.getGlobalDescribe().get('SimulacaoCredito__c').getDescribe();
        DescribeFieldResult periodicidadeResult = objResult.fields.getMap().get('Periodicidade__c').getDescribe();
        DescribeFieldResult tipoIOFResult = objResult.fields.getMap().get('TipoIOF__c').getDescribe();
        List<Schema.PicklistEntry> lstPeriodicidadePicklistEntry = periodicidadeResult.getPicklistValues();
        List<Schema.PicklistEntry> lstTipoIOFPicklistEntry = tipoIOFResult.getPicklistValues();

        return this.factory.construirObjPicklistSimulacao(lstPeriodicidadePicklistEntry, lstTipoIOFPicklistEntry);
    }

    public void salvarSimulacao(Id recordId, FormalizacaoSchema.SimularParcelasLwcRequest objRequest, FormalizacaoSchema.SimularParcelasResponse objResponse){
        Id accountId = recordId?.getSObjectType().getDescribe().getName() == 'Account' ? recordId : null;
        Id leadId = accountId == null ? recordId : null;
    
        SimulacaoCredito__c simulacaoCredito = this.factory.construirObjSimulacaoCredito(accountId, leadId, objRequest, objResponse);
        this.formalizacao.salvarSimulacaoCredito(simulacaoCredito);

        List<SimulacaoParcela__c> lstSimulacaoParcela = this.factory.construirObjSimulacaoParcela(simulacaoCredito.Id, objResponse);
        this.formalizacao.salvarSimulacoesParcela(lstSimulacaoParcela);
    }

}