force-app/main/default/objects/Filial__c/Filial__c.object-meta.xml
<CustomObject>
    <label>Filial</label>
    <nameField>
        <label>Filial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filiais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filial__c/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <externalId>true</externalId>
    <label>Código filial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/CodigoFilial__c.field-meta.xml
<CustomField>
    <fullName>CodigoFilial__c</fullName>
    <label>Código Filial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Filial__c.field-meta.xml
<CustomField>
    <fullName>Filial__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; IdFilial__c, IdFilial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretor</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Gestor(a)</fullName>
            </value>
            <value>
                <fullName>Analista</fullName>
            </value>
            <value>
                <fullName>Analista SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NegociacaoRepository.cls
public class NegociacaoRepository {

    public List<ProcessInstanceStep> buscarEtapasMaisRecenteAprovadas(Set<Id> setObjIds) {
        return [
            SELECT 
                Id,
                ProcessInstance.CreatedById,
                ProcessInstance.Status,
                ProcessInstance.TargetObjectId,
                ProcessInstance.LastActor.Funcao__c,
                ProcessInstance.ProcessDefinition.DeveloperName,
                StepStatus
            FROM 
                ProcessInstanceStep 
            WHERE 
                ProcessInstance.TargetObjectId IN: setObjIds
            AND
                StepStatus IN ('Approved', 'Rejected')
            WITH
                SYSTEM_MODE
            ORDER BY
                ProcessInstance.LastModifiedDate ASC
        ];
    }

    public List<Filial__c> buscarFilialPorCodigo(Set<String> docFilial) {
        return [
            SELECT 
                Id,
                CodigoFilial__c
            FROM 
                Filial__c 
            WHERE 
                CodigoFilial__c IN: docFilial
            WITH
                USER_MODE
        ];
    }

    public List<User> buscarHierarquiaUsuariosPorSetId(Set<Id> setUserIds){
        return [
            SELECT
                Id,
                Name,
                Manager.Funcao__c,
                Manager.Manager.Funcao__c,
                Manager.Manager.Manager.Funcao__c,
                Manager.Manager.Manager.Manager.Funcao__c,
                Manager.Manager.Manager.Manager.Manager.Funcao__c,
                Manager.Manager.Manager.Manager.Manager.Manager.Funcao__c
            FROM
                User
            WHERE
                Id IN: setUserIds
        ];
    }

    public List<ProcessInstanceWorkItem> buscarItensPendentesAprovacao(Set<Id> setObjIds) {
        return [
            SELECT 
                Id,
                ProcessInstance.Status,
                ProcessInstance.TargetObjectId
            FROM 
                ProcessInstanceWorkItem 
            WHERE 
                ProcessInstance.TargetObjectId IN: setObjIds
            WITH
                SYSTEM_MODE
        ];
    }

    public List<Opportunity> buscarOportunidadesPorSetId(Set<Id> setOpportunityIds) {
        return [
            SELECT
                Id,
                OwnerId,
                StageName
            FROM
                Opportunity
            WHERE
                Id IN: setOpportunityIds
        ];
    }

    public List<User> buscarUsuariosPorSetId(Set<Id> setUserIds){
        return [
            SELECT 
                Id,
                Name,
                Funcao__c
            FROM 
                User
            WHERE
                Id IN: setUserIds
            WITH
                USER_MODE
        ];
    }

    public User buscarUsuarioPorId(Id userId){
        List<User> listUser = buscarUsuariosPorSetId(new Set<Id> { userId });
        return !listUser.isEmpty() ? listUser[0] : null;
    }

}