force-app/main/default/objects/Endpoint__mdt/fields/ChaveCliente__c.field-meta.xml
<CustomField>
    <fullName>ChaveCliente__c</fullName>
    <label>Chave do cliente</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endpoint__mdt/fields/CredencialNomeada__c.field-meta.xml
<CustomField>
    <fullName>CredencialNomeada__c</fullName>
    <label>Credencial nomeada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EuroSecuritizadora</fullName>
                <label>Euro Securitizadora</label>
            </value>
            <value>
                <fullName>FlowFinanceAPI</fullName>
                <label>Flow Finance API</label>
            </value>
            <value>
                <fullName>FlowFinanceAuth</fullName>
                <label>Flow Finance Auth</label>
            </value>
            <value>
                <fullName>Protheus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Endpoint__mdt/fields/SegredoCliente__c.field-meta.xml
<CustomField>
    <fullName>SegredoCliente__c</fullName>
    <label>Segredo do cliente</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracao__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomAuthenticationSimularParcelas.cls
public with sharing class CustomAuthenticationSimularParcelas {

    public static String getTokenParcelas() {
        String accessToken;
        Endpoint__mdt endpoint = [SELECT Id, ChaveCliente__c, CredencialNomeada__c, SegredoCliente__c FROM Endpoint__mdt WHERE DeveloperName =: 'SimularParcelasTokenHost'];
        Integracao__mdt integracao = [SELECT Id, Path__c FROM Integracao__mdt WHERE DeveloperName =: 'SimularParcelasTokenPath'];
        String tokenUrl = 'callout:' + endpoint.CredencialNomeada__c + integracao.Path__c;

        String body = 'grant_type=client_credentials';
        Blob credentials = Blob.valueOf(endpoint.ChaveCliente__c + ':' + endpoint.SegredoCliente__c);
        String credentialsStr = 'Basic ' + EncodingUtil.base64Encode(credentials);

        Map<String, String> headers = new Map<String, String>{'Accept' => 'application/json', 'Authorization' => credentialsStr, 'Content-Type' => 'application/x-www-form-urlencoded'};
        HttpResponse response = Bdrs.Callout.executeHttpRequest(tokenUrl, 'POST', headers, body, 15000);

        Map<String, Object> deserializedResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
        if(deserializedResponse.containsKey('access_token'))
            accessToken = String.valueOf(deserializedResponse.get('access_token'));

        return accessToken;

    }
}