force-app/main/default/objects/Endpoint__mdt/fields/CredencialNomeada__c.field-meta.xml
<CustomField>
    <fullName>CredencialNomeada__c</fullName>
    <label>Credencial nomeada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EuroSecuritizadora</fullName>
                <label>Euro Securitizadora</label>
            </value>
            <value>
                <fullName>FlowFinanceAPI</fullName>
                <label>Flow Finance API</label>
            </value>
            <value>
                <fullName>FlowFinanceAuth</fullName>
                <label>Flow Finance Auth</label>
            </value>
            <value>
                <fullName>Protheus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integracao__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomAuthenticationService.cls
public class CustomAuthenticationService {

    public static String getToken() {
        String accessToken;
        Endpoint__mdt endpoint = [SELECT Id, CredencialNomeada__c FROM Endpoint__mdt WHERE DeveloperName =: 'Protheus'];
        Integracao__mdt integracao = [SELECT Id, Path__c FROM Integracao__mdt WHERE DeveloperName =: 'ProtheusToken'];
        String tokenUrl = 'callout:' + endpoint.CredencialNomeada__c + integracao.Path__c;

        Map<String, String> headers = new Map<String, String>{'Accept' => 'application/json'};
        HttpResponse response = Bdrs.Callout.executeHttpRequest(tokenUrl, 'POST', headers, null, 15000);

        if(Test.isRunningTest())
            accessToken = 'TOKEN_ACESSO';
        else{
            Map<String, Object> deserializedResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());  
            
            if(deserializedResponse.containsKey('access_token'))
                accessToken = String.valueOf(deserializedResponse.get('access_token')); 
        }
        
        return accessToken;
    }
    
}