force-app/main/default/objects/Endpoint__mdt/fields/CredencialNomeada__c.field-meta.xml
<CustomField>
    <fullName>CredencialNomeada__c</fullName>
    <label>Credencial nomeada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EuroSecuritizadora</fullName>
                <label>Euro Securitizadora</label>
            </value>
            <value>
                <fullName>FlowFinanceAPI</fullName>
                <label>Flow Finance API</label>
            </value>
            <value>
                <fullName>FlowFinanceAuth</fullName>
                <label>Flow Finance Auth</label>
            </value>
            <value>
                <fullName>Protheus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integracao__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClienteService.cls
public with sharing class ClienteService {

    public static SendClienteWorkRunSchema.Response sendRequest(String clienteServiceRequest) {
        SendClienteWorkRunSchema.Request sendClienteWorkRunReqObj = (SendClienteWorkRunSchema.Request) System.JSON.deserialize(clienteServiceRequest, SendClienteWorkRunSchema.Request.class);
        SendClienteWorkRunSchema.Response sendClienteWorkRunResObj = new SendClienteWorkRunSchema.Response();

        Endpoint__mdt endpoint = [SELECT Id, CredencialNomeada__c FROM Endpoint__mdt WHERE DeveloperName =: 'Protheus'];
        Integracao__mdt integracao = [SELECT Id, Path__c FROM Integracao__mdt WHERE DeveloperName =: 'ProtheusInclusaoCliente'];
        String apiUrl = 'callout:' + endpoint.CredencialNomeada__c + integracao.Path__c;
        String accessToken = 'Bearer ' + CustomAuthenticationService.getToken();
        Map<String, String> headers = new Map<String, String>{'Content-Type' => 'application/json', 'Authorization' => accessToken};

        HttpResponse response = Bdrs.Callout.executeHttpRequest(apiUrl, 'POST', headers, JSON.serialize(sendClienteWorkRunReqObj.clienteRequest), 15000);

        if(response.getStatusCode() == 201)
            sendClienteWorkRunResObj.sucesso = true;
        else {
            if(response.getBody()?.contains('pode haver mais de um registro de'))
                sendClienteWorkRunResObj.sucesso = false;
            else{
                throw new HandledException(
                    String.format('Http status: {0}\n | Erro: {1}', new List<String> {
                        String.valueOf(response.getStatusCode()),
                        response.getBody()})
                );
            }
        }

        sendClienteWorkRunResObj.response = response.getBody();

        return sendClienteWorkRunResObj;
    }
}