force-app/main/default/objects/Lead/fields/ComporRenda__c.field-meta.xml
<CustomField>
    <fullName>ComporRenda__c</fullName>
    <label>Compor renda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <inlineHelpText>Informe o CPF para Pessoa Física ou CNPJ para Pessoa Jurídica.</inlineHelpText>
    <label>Documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EstadoCivil__c.field-meta.xml
<CustomField>
    <fullName>EstadoCivil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solteiro</fullName>
            </value>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Divorciado</fullName>
            </value>
            <value>
                <fullName>Viúvo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Originador__c.field-meta.xml
<CustomField>
    <fullName>Originador__c</fullName>
    <label>Originador</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Redes sociais</fullName>
            </value>
            <value>
                <fullName>Orgânico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <inlineHelpText>Preencher nos casos de empréstimo com veículo ou veículo pesado em garantia.</inlineHelpText>
    <label>Placa</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrazoOperacao__c.field-meta.xml
<CustomField>
    <fullName>PrazoOperacao__c</fullName>
    <inlineHelpText>Informar prazo em meses</inlineHelpText>
    <label>Prazo da operação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ProdutoInteresse__c.field-meta.xml
<CustomField>
    <fullName>ProdutoInteresse__c</fullName>
    <label>Produto de interesse</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Antecipação de recebíveis</fullName>
            </value>
            <value>
                <fullName>Conta Escrow</fullName>
            </value>
            <value>
                <fullName>Giro Parcelado</fullName>
            </value>
            <value>
                <fullName>Capital de Giro</fullName>
            </value>
            <value>
                <fullName>Financiamento de imóvel</fullName>
            </value>
            <value>
                <fullName>Financiamento de veículo</fullName>
            </value>
            <value>
                <fullName>Empréstimo com imóvel em garantia</fullName>
            </value>
            <value>
                <fullName>Empréstimo com veiculo em garantia</fullName>
            </value>
            <value>
                <fullName>Empréstimo com veiculo pesado em garantia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ProdutoNegociar__c.field-meta.xml
<CustomField>
    <fullName>ProdutoNegociar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto a negociar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Restricao__c.field-meta.xml
<CustomField>
    <fullName>Restricao__c</fullName>
    <inlineHelpText>Preencher nos casos de empréstimo com veículo em garantia.</inlineHelpText>
    <label>Restrição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TipoPessoa__c.field-meta.xml
<CustomField>
    <fullName>TipoPessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pessoa física</fullName>
            </value>
            <value>
                <fullName>Pessoa jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ValorBem__c.field-meta.xml
<CustomField>
    <fullName>ValorBem__c</fullName>
    <inlineHelpText>Informar o valor do veículo ou imóvel.</inlineHelpText>
    <label>Valor do bem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ValorFinanciamento__c.field-meta.xml
<CustomField>
    <fullName>ValorFinanciamento__c</fullName>
    <label>Valor do financiamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/OperacoesEstruturadas.recordType-meta.xml
<RecordType>
    <fullName>OperacoesEstruturadas</fullName>
    <active>true</active>
    <businessProcess>Securitizadora</businessProcess>
    <label>Operações estruturadas</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/ProdutosFinanceiros.recordType-meta.xml
<RecordType>
    <fullName>ProdutosFinanceiros</fullName>
    <active>true</active>
    <businessProcess>Securitizadora</businessProcess>
    <label>Produtos Financeiros</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ComporRenda__c.field-meta.xml
<CustomField>
    <fullName>ComporRenda__c</fullName>
    <label>Compor renda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>Account.Documento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Placa__c.field-meta.xml
<CustomField>
    <fullName>Placa__c</fullName>
    <label>Placa</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrazoOperacao__c.field-meta.xml
<CustomField>
    <fullName>PrazoOperacao__c</fullName>
    <inlineHelpText>Informar prazo em meses</inlineHelpText>
    <label>Prazo da Operação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorBem__c.field-meta.xml
<CustomField>
    <fullName>ValorBem__c</fullName>
    <label>Valor do bem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorFinanciamento__c.field-meta.xml
<CustomField>
    <fullName>ValorFinanciamento__c</fullName>
    <label>Valor do financiamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/OperacoesEstruturadas.recordType-meta.xml
<RecordType>
    <fullName>OperacoesEstruturadas</fullName>
    <active>true</active>
    <businessProcess>Oportunidades Securitizadora</businessProcess>
    <label>Operações estruturadas</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/ProdutosFinanceiros.recordType-meta.xml
<RecordType>
    <fullName>ProdutosFinanceiros</fullName>
    <active>true</active>
    <businessProcess>Produtos Financeiros</businessProcess>
    <label>Produtos financeiros</label>
</RecordType>

force-app/main/default/objects/RendaComplementar__c/RendaComplementar__c.object-meta.xml
<CustomObject>
    <label>Renda Complementar</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Nome de Renda Complementar</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rendas Complementares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RendaComplementar__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RendaComplementar__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RendaComplementar__c/fields/EstadoCivil__c.field-meta.xml
<CustomField>
    <fullName>EstadoCivil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado(a)</fullName>
            </value>
            <value>
                <fullName>Divorciado(a)</fullName>
            </value>
            <value>
                <fullName>Separado(a)</fullName>
            </value>
            <value>
                <fullName>Solteiro(a)</fullName>
            </value>
            <value>
                <fullName>União estável</fullName>
            </value>
            <value>
                <fullName>Viúvo(a)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RendaComplementar__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Rendas Complementares</relationshipLabel>
    <relationshipName>RendasComplementares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RendaComplementar__c/fields/NomeCompleto__c.field-meta.xml
<CustomField>
    <fullName>NomeCompleto__c</fullName>
    <label>Nome completo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RendaComplementar__c/fields/Renda__c.field-meta.xml
<CustomField>
    <fullName>Renda__c</fullName>
    <label>Renda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RendaComplementar__c/fields/TipoPessoa__c.field-meta.xml
<CustomField>
    <fullName>TipoPessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pessoa física</fullName>
            </value>
            <value>
                <fullName>Pessoa jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaptacaoClienteFactory.cls
public class CaptacaoClienteFactory {

    private CaptacaoClienteRepository repository = new CaptacaoClienteRepository();

    //Realiza parse de CaptacaoClienteSchema.LeadRequest para Lead
    public Lead gerarObjetoLead(CaptacaoClienteSchema.LeadRequest leadRequest) {

        String documentoFormatado = Format.documento(leadRequest.documento);
        Id idProduto;
        Id idTipoRegistro;
        Lead novoLead = new Lead();

        switch on leadRequest.origem {
            when 'Site Euro Securitizadora', 'Site Euro Prime Securitizadora' {
                idTipoRegistro = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('OperacoesEstruturadas').getRecordTypeId();
                if(leadRequest.produtoInteresse == 'Antecipação de recebíveis' || leadRequest.produtoInteresse == 'Giro Parcelado' || leadRequest.produtoInteresse == 'Conta Escrow') {
                    idProduto = [SELECT Id, Name FROM Product2 WHERE Name =:'Capital de giro'].Id;
                }

                String telefone = Bdrs.Format.clearNumberFormatting(leadRequest.telefone);
                novoLead = new Lead(
                    LastName = leadRequest.nome,
                    Documento__c = documentoFormatado,
                    Email = leadRequest.email,
                    MobilePhone = telefone.length() == 11 ? telefone : null,
                    Phone = telefone.length() != 11 ? telefone : null,
                    LeadSource = leadRequest.origem,
                    TipoPessoa__c = documentoFormatado.length() == 18 ? 'Pessoa jurídica' : 'Pessoa física',
                    ProdutoNegociar__c = idProduto,
                    ProdutoInteresse__c = leadRequest.produtoInteresse,
                    RecordTypeId = idTipoRegistro
                );
            }
            when 'Site Euro 17 Crédito' {
                idTipoRegistro = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('ProdutosFinanceiros').getRecordTypeId();

                if(leadRequest.produtoInteresse != null) {
                    idProduto = repository.buscarProdutoPorNome(leadRequest.produtoInteresse).Id;
                }

                novoLead =  new Lead(
                    LastName = leadRequest.nome,
                    Email = leadRequest.email,
                    Documento__c = documentoFormatado,
                    LeadSource = leadRequest.origem,
                    TipoPessoa__c = documentoFormatado.length() == 18 ? 'Pessoa jurídica' : 'Pessoa física',
                    Phone = leadRequest.telefone,
                    MobilePhone = leadRequest.celular,
                    ComporRenda__c = leadRequest.comporRenda,
                    ValorBem__c = leadRequest.valorImovel,
                    ValorFinanciamento__c = leadRequest.valorFinanciamento,
                    PrazoOperacao__c = leadRequest.prazo,
                    Placa__c = leadRequest.placa,
                    Restricao__c = leadRequest.restricao,
                    Originador__c = leadRequest.originador,
                    ProdutoNegociar__c = idProduto,
                    RecordTypeId = idTipoRegistro
                );
            }
            when else {
                throw new CaptacaoCliente.CaptacaoClienteException('Erro na criação do lead: Origem não mapeada');
            }
        }

        return novoLead;
    }

    //Realiza parse de CaptacaoClienteSchema.LeadRequest para Oportunidade
    public Opportunity gerarObjetoOportunidade(CaptacaoClienteSchema.LeadRequest leadRequest, String fase) {
        return new Opportunity(
            Name = leadRequest.nome,
            AccountId = leadRequest.contaExistenteId,
            CloseDate = System.today(),
            StageName =  fase,
            LeadSource = leadRequest.origem
        );
    }

    //Realiza parse de CaptacaoClienteSchema.LeadRequest para RendaComplementar
    public RendaComplementar__c gerarObjetoRendaComplementar(CaptacaoClienteSchema.LeadRequest leadRequest, Id idLead) {
        String documentoFormatado = Format.documento(leadRequest.documento);

        return new RendaComplementar__c(
            NomeCompleto__c = leadRequest.nome,
            TipoRenda__c = 'Principal',
            Email__c = leadRequest.email,
            Documento__c = documentoFormatado,
            TipoPessoa__c = documentoFormatado.length() == 18 ? 'Pessoa jurídica' : 'Pessoa física',
            Telefone__c = leadRequest.telefone,
            Celular__c = leadRequest.celular,
            EstadoCivil__c = leadRequest.estadoCivil,
            Renda__c = leadRequest.renda,
            Lead__c = idLead
        );
    }
}