force-app/main/default/objects/Lead/fields/TelefoneInternacional__c.field-meta.xml
<CustomField>
    <fullName>TelefoneInternacional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo de controle para evitar validações e máscaras de números nacionais para números de telefone internacionais informados.</description>
    <label>Telefone internacional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler  extends TriggerHandler{

    private CaptacaoClienteService service = new CaptacaoClienteService();
    private List<Lead> lstLeadsCelularFormat;
    private List<Lead> lstLeadsTelefoneFormat;

    public LeadTriggerHandler(){
        this.lstLeadsCelularFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'CelularInternacional__c', false);
        this.lstLeadsTelefoneFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'TelefoneInternacional__c', false);
    }

    public override void beforeInsert(){
        this.service.formatarDocumentoLead(Trigger.new);
        Bdrs.Phone.validateAndFormat(this.lstLeadsTelefoneFormat, Lead.Phone, false);
        Bdrs.Phone.validateAndFormat(this.lstLeadsCelularFormat, Lead.MobilePhone, true);
    }

    public override void beforeUpdate(){
        this.service.formatarDocumentoLead(Trigger.new);
        Bdrs.Phone.validateAndFormat(this.lstLeadsTelefoneFormat, Lead.Phone, false);
        Bdrs.Phone.validateAndFormat(this.lstLeadsCelularFormat, Lead.MobilePhone, true);
    }
}