force-app/main/default/objects/SimulacaoCredito__c/SimulacaoCredito__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar as simulações retornadas pelo FlowFinance durante o cálculo de parcelas.</description>
    <label>Simulação de crédito</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulações de crédito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SimulacaoParcela__c/SimulacaoParcela__c.object-meta.xml
<CustomObject>
    <description>Objeto filho de Simulação de crédito, onde as parcelas serão armazenadas como registros contendo valores de juros e amortização de cada uma.</description>
    <label>Simulação de parcela</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulações de parcela</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SimulacaoParcela__c/fields/SimulacaoCredito__c.field-meta.xml
<CustomField>
    <fullName>SimulacaoCredito__c</fullName>
    <label>Simulação de crédito</label>
    <referenceTo>SimulacaoCredito__c</referenceTo>
    <relationshipLabel>Simulações de parcela</relationshipLabel>
    <relationshipName>SimulacoesParcela</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Formalizacao.cls
public class Formalizacao {

    public void salvarSimulacaoCredito(SimulacaoCredito__c simulacaoCredito){
        try {
            insert simulacaoCredito;
        } catch (Exception ex) {
            throw new FormalizacaoException(ex.getMessage());
        }
    }

    public void salvarSimulacoesParcela(List<SimulacaoParcela__c> listSimulacaoParcela){
        try {
            insert listSimulacaoParcela;
        } catch (Exception ex) {
            throw new FormalizacaoException(ex.getMessage());
        }
    }

    public class FormalizacaoException extends Exception {}

}