force-app/main/default/objects/Contact/fields/CelularInternacional__c.field-meta.xml
<CustomField>
    <fullName>CelularInternacional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo de controle para evitar validações e máscaras de números nacionais para números de celular internacionais informados.</description>
    <label>Celular internacional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler extends Bdrs.TriggerHandler{

    private List<Contact> lstContatosCelularFormat;
    private List<Contact> lstContatosTelefoneFormat;

    public ContactTriggerHandler(){
        this.lstContatosCelularFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'CelularInternacional__c', false);
        this.lstContatosTelefoneFormat = Util.retornarListaFiltradaCampoBoolean(Trigger.new, 'TelefoneInternacional__c', false);
    }

    public override void beforeInsert(){
        Bdrs.Phone.validateAndFormat(this.lstContatosTelefoneFormat, Contact.Phone, false);
        Bdrs.Phone.validateAndFormat(this.lstContatosCelularFormat, Contact.MobilePhone, true);
    }

    public override void beforeUpdate(){
        Bdrs.Phone.validateAndFormat(this.lstContatosTelefoneFormat, Contact.Phone, false);
        Bdrs.Phone.validateAndFormat(this.lstContatosCelularFormat, Contact.MobilePhone, true);
    }

}