force-app/main/default/objects/Comissao__c/Comissao__c.object-meta.xml
<CustomObject>
    <label>Comissão</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Número da Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissao__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Comissões</relationshipLabel>
    <relationshipName>Comissoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comissionado__c/Comissionado__c.object-meta.xml
<CustomObject>
    <label>Comissionado</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Nome de Comissionado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissionados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissionado__c/fields/Comissao__c.field-meta.xml
<CustomField>
    <fullName>Comissao__c</fullName>
    <label>Comissão</label>
    <referenceTo>Comissao__c</referenceTo>
    <relationshipLabel>Comissionado</relationshipLabel>
    <relationshipName>Comissionados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comissionado__c/fields/Comissionado__c.field-meta.xml
<CustomField>
    <fullName>Comissionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comissionado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Comissionados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comissionado__c/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <formula>TEXT(Comissionado__r.Funcao__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Função</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comissionado__c/fields/PercentualComissao__c.field-meta.xml
<CustomField>
    <fullName>PercentualComissao__c</fullName>
    <label>Percentual da comissão</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Comissionado__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>Comissao__r.Oportunidade__r.UnidadeNegocio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemComissionado__mdt/ItemComissionado__mdt.object-meta.xml
<CustomObject>
    <label>Item Comissionado</label>
    <pluralLabel>Itens Comissionado</pluralLabel>
</CustomObject>

force-app/main/default/objects/ItemComissionado__mdt/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
                <default>true</default>
                <label>Gerente de negócio</label>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretoria</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Célula de retenção</fullName>
            </value>
            <value>
                <fullName>Time de relacionamento</fullName>
            </value>
            <value>
                <fullName>Gerente de relacionamento principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ItemComissionado__mdt/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comissionado__c.field-meta.xml
<CustomField>
    <fullName>Comissionado__c</fullName>
    <label>Comissionado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ValorOportunidade__c</fullName>
    <label>Valor da Oportunidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/TimeRelacionamento__c.object-meta.xml
<CustomObject>
    <label>Time de Relacionamento</label>
    <nameField>
        <displayFormat>TMR - {0000}</displayFormat>
        <label>Nome de Time de Relacionamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times de Relacionamento</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeRelacionamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Times de Relacionamento</relationshipLabel>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/DivisaoComissao__c.field-meta.xml
<CustomField>
    <fullName>DivisaoComissao__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Divisão de comissão</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <formula>TEXT(NomeGerente__r.Funcao__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Função</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/NomeGerente__c.field-meta.xml
<CustomField>
    <fullName>NomeGerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Times de Relacionamento</relationshipLabel>
    <relationshipName>TimesRelacionamento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>TEXT( NomeGerente__r.UnidadeNegocio__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeRelacionamento__c/recordTypes/TimeRelacionamento.recordType-meta.xml
<RecordType>
    <fullName>TimeRelacionamento</fullName>
    <active>true</active>
    <description>Cadastro dos gerentes relacionados à oportunidade</description>
    <label>Time de relacionamento</label>
</RecordType>

force-app/main/default/classes/ComissaoFactory.cls
public class ComissaoFactory {
    
    //Gera registro de comissão de uma oportunidade
    public Comissao__c gerarComissao(Opportunity oportunidade) {   
        Comissao__c comissao = new Comissao__c(
            Oportunidade__c = oportunidade.Id
        );
        
        return comissao;
    }

    //Gera ComissaoContext com os dados de Comissao e Oportunidade
    public ComissaoSchema.ComissaoContext gerarComissaoContext(Comissao__c comissaoObj, Opportunity oportunidade) {
        ComissaoSchema.ComissaoContext context = new ComissaoSchema.ComissaoContext();
        
        context.comissao = comissaoObj;
        context.conta = oportunidade.Account;
        context.unidadeNegocio = oportunidade.UnidadeNegocio__c;
        context.valorOportunidade = oportunidade.ValorOportunidade__c;
        context.tipoNegociacao = oportunidade.Type;
        context.timeRelacionamento = oportunidade.TimesRelacionamento__r;
        context.tipoComissao = null; //Deve ser encontrado dentro das regras de cada fluxo
        
        return context;
    }

    //Gera Comissionado
    public ComissaoSchema.Comissionado gerarComissionado(Id usuarioId, ItemComissionado__mdt metaComissionado) {
        ComissaoSchema.Comissionado comissionado = new ComissaoSchema.Comissionado();
        
        comissionado.funcao = metaComissionado.Funcao__c;
        comissionado.percentual = metaComissionado.Percentual__c;
        comissionado.usuarioId = usuarioId;
        
        return comissionado;
    }

    //Gera Comissionados através de Grupo publico ou Fila
    public List<ComissaoSchema.Comissionado> gerarComissionado(List<GroupMember> membrosGrupo, ItemComissionado__mdt metaComissionado, Boolean dividirPercentual) {
        List<ComissaoSchema.Comissionado> comissionados = new List<ComissaoSchema.Comissionado>();
        ComissaoSchema.Comissionado comissionado;
        Decimal percentual = metaComissionado.Percentual__c;

        if(dividirPercentual && membrosGrupo.size() > 0) {
            percentual = metaComissionado.Percentual__c / membrosGrupo.size();
        }

        for(GroupMember membro : membrosGrupo) {
            comissionado = new ComissaoSchema.Comissionado();
            comissionado.funcao = metaComissionado.Funcao__c;
            comissionado.percentual = percentual;
            comissionado.usuarioId = membro.UserOrGroupId;

            comissionados.add(comissionado);
        }
        
        return comissionados;
    }

    //Gera Comissionado__c através de ComissaoSchema.Comissionado
    public List<Comissionado__c> gerarComissionado(ComissaoSchema.ComissaoContext context, List<ComissaoSchema.Comissionado> comissionados) {
        List<Comissionado__c> comissionadosObj = new List<Comissionado__c>();

        for(ComissaoSchema.Comissionado comissionado : comissionados) {
            comissionadosObj.add(new Comissionado__c(
                Comissao__c = context.comissao.Id,
                Comissionado__c = comissionado.usuarioId,
                PercentualComissao__c = comissionado.percentual
            ));
        }
        
        return comissionadosObj;
    }

    //Gera Comissionado considerando apenas o time de relacionamento
    public ComissaoSchema.Comissionado gerarComissionado(TimeRelacionamento__c pessoaTimeRelacionamento) {
        ComissaoSchema.Comissionado comissionado = new ComissaoSchema.Comissionado();
        
        comissionado.funcao = pessoaTimeRelacionamento.Funcao__c;
        comissionado.percentual = pessoaTimeRelacionamento.DivisaoComissao__c;
        comissionado.usuarioId = pessoaTimeRelacionamento.NomeGerente__c;
        
        return comissionado;
    }

    //Gera Comissionado considerando o time de relacionamento e o valor do metadado
    public ComissaoSchema.Comissionado gerarComissionado(TimeRelacionamento__c pessoaTimeRelacionamento, List<ItemComissionado__mdt> itensComissionados, String funcao) {
        ComissaoSchema.Comissionado comissionado = new ComissaoSchema.Comissionado();

        for(ItemComissionado__mdt metaComissionado : itensComissionados) {
            if(funcao == metaComissionado.Funcao__c){
                comissionado.funcao = pessoaTimeRelacionamento.Funcao__c;
                comissionado.percentual = metaComissionado.Percentual__c;
                comissionado.usuarioId = pessoaTimeRelacionamento.NomeGerente__c;
            }
        }
 
        return comissionado;
    }

    //Gera Comissionados através da Hierarquia do usuário e Metadados
    public List<ComissaoSchema.Comissionado> gerarComissionado(Map<String, Id> hierarquiaGerente, List<ItemComissionado__mdt> itensComissionados, List<GroupMember> diretoria) {
        List<ComissaoSchema.Comissionado> comissionados = new List<ComissaoSchema.Comissionado>();
        ComissaoSchema.Comissionado comissionado;

        for(ItemComissionado__mdt metaComissionado : itensComissionados) {
            Id usuarioHierarquiaId = hierarquiaGerente.get(metaComissionado.Funcao__c);

            if(usuarioHierarquiaId != null && (metaComissionado.Funcao__c != 'Gerente de negócio' && metaComissionado.Funcao__c != 'Gerente de relacionamento principal')) {
                comissionado = new ComissaoSchema.Comissionado();
                comissionado.funcao = metaComissionado.Funcao__c;
                comissionado.percentual = metaComissionado.Percentual__c;
                comissionado.usuarioId = usuarioHierarquiaId;

                comissionados.add(comissionado);
            }

            if (metaComissionado.Funcao__c == 'Diretoria') {
                comissionados.addAll(this.gerarComissionado(diretoria, metaComissionado, true));
            }
        }
        
        return comissionados;
    }
}