force-app/main/default/objects/Comissao__c/Comissao__c.object-meta.xml
<CustomObject>
    <label>Comissão</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Número da Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade de Negócio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Investimentos.recordType-meta.xml
<RecordType>
    <fullName>Investimentos</fullName>
    <active>true</active>
    <businessProcess>Oportunidades Captação e Investimento</businessProcess>
    <label>Investimentos</label>
</RecordType>

force-app/main/default/objects/User/fields/Funcao__c.field-meta.xml
<CustomField>
    <fullName>Funcao__c</fullName>
    <label>Função</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gerente de negócio</fullName>
            </value>
            <value>
                <fullName>Gerente geral</fullName>
            </value>
            <value>
                <fullName>Superintendente</fullName>
            </value>
            <value>
                <fullName>Diretor</fullName>
            </value>
            <value>
                <fullName>Vice presidencia</fullName>
            </value>
            <value>
                <fullName>Presidente</fullName>
            </value>
            <value>
                <fullName>Ex gerente parceiro</fullName>
            </value>
            <value>
                <fullName>Ex gerente inativo</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Ex gerente exceção</fullName>
            </value>
            <value>
                <fullName>Gestor(a)</fullName>
            </value>
            <value>
                <fullName>Analista</fullName>
            </value>
            <value>
                <fullName>Analista SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/UnidadeNegocio__c.field-meta.xml
<CustomField>
    <fullName>UnidadeNegocio__c</fullName>
    <label>Unidade de negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operações estruturadas</fullName>
            </value>
            <value>
                <fullName>Investimentos</fullName>
            </value>
            <value>
                <fullName>Produtos financeiros</fullName>
            </value>
            <value>
                <fullName>Formalização</fullName>
            </value>
            <value>
                <fullName>Crédito</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>SAC/Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Comissao.cls
public class Comissao {
    private ComissaoRepository repository = new ComissaoRepository();
    private ComissaoFactory factory = new ComissaoFactory();
    
    //Retornas apenas as oportunidades fechadas e ganhas
    public List<Opportunity> retornarOportunidadesGanhas(List<Opportunity> oportunidades, Map<Id, Opportunity> mapOpportunityOld) {
        List<Opportunity> oportunidadesGanhas = new List<Opportunity>();

        for(Opportunity opp : oportunidades) {
            Opportunity oportunidadeOld = mapOpportunityOld.get(opp.Id);
            String faseFechadaGanha = opp.UnidadeNegocio__c == 'Produtos financeiros' ? 'Contrato registrado' : 'Contrato assinado';
        
            if(oportunidadeOld.StageName != opp.StageName && opp.StageName == faseFechadaGanha) {
                oportunidadesGanhas.add(opp);
            }
        }

        return oportunidadesGanhas;
    }

    //Retorna qual fluxo de comissão deverá ser executado
    public IFluxoComissao encontrarFluxoComissao(ComissaoSchema.ComissaoContext context) {
        //TODO: REVISAR SE OS NOMES DOS DEPARTAMENTOS SERAO ESSES MESMO

        Map<String, IFluxoComissao> mapFluxos = new  Map<String, IFluxoComissao>{
            'Operações estruturadas' => null,
            'Investimentos' => new ComissaoInvestimentoCommand(),
            'Produtos financeiros' => new ComissaoProdFinanceirosCommand()
        };

        return mapFluxos.get(context.unidadeNegocio);
    }

    //De acordo com os parametros de oportunidade, gera objeto de context
    public ComissaoSchema.ComissaoContext retornarComissaoContext(Comissao__c comissaoObj, Opportunity oportunidade) {
        //Busca oporturnidade e todos os dados necessários
        oportunidade = this.repository.buscarDetalhesOportunidade(new Set<Id> {oportunidade.Id}).get(0);

        ComissaoSchema.ComissaoContext context = this.factory.gerarComissaoContext(comissaoObj, oportunidade);

        return context;
    }

    //Retorna membros da hierarquia do usuário passado por parametro
    //TODO: FUTURAMENTE CRIAR ESTE MAP DE FORMA RECURSIVA, PREVENINDO MUDANCAS NA ESTRUTURA
    public Map<String, Id> encontrarMembrosHierarquia(Id usuarioId) {
        Map<String, Id> hierarquiaGerente = new Map<String, Id>();
        User gerente = this.repository.buscarHierarquiaUsuario(usuarioId).get(0);

        //GG
        hierarquiaGerente.put(gerente.Manager.Funcao__c, gerente.ManagerId);

        //Superindente
        hierarquiaGerente.put(gerente.Manager.Manager.Funcao__c, gerente.Manager.ManagerId);

        //Diretor
        hierarquiaGerente.put(gerente.Manager.Manager.Manager.Funcao__c, gerente.Manager.Manager.ManagerId);

        //VP
        hierarquiaGerente.put(gerente.Manager.Manager.Manager.Manager.Funcao__c, gerente.Manager.Manager.Manager.ManagerId);

        return hierarquiaGerente;
    }
}