force-app/main/default/objects/Comissao__c/Comissao__c.object-meta.xml
<CustomObject>
    <label>Comissão</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Número da Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissões</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissionado__c/Comissionado__c.object-meta.xml
<CustomObject>
    <label>Comissionado</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Nome de Comissionado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comissionados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comissionado__c/fields/Comissao__c.field-meta.xml
<CustomField>
    <fullName>Comissao__c</fullName>
    <label>Comissão</label>
    <referenceTo>Comissao__c</referenceTo>
    <relationshipLabel>Comissionado</relationshipLabel>
    <relationshipName>Comissionados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comissionado__c/fields/Comissionado__c.field-meta.xml
<CustomField>
    <fullName>Comissionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comissionado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Comissionados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comissionado__c.field-meta.xml
<CustomField>
    <fullName>Comissionado__c</fullName>
    <label>Comissionado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcessamentoComissionadosQueueable.cls
public class ProcessamentoComissionadosQueueable implements Queueable {
    private Comissao__c comissaoObj;
    private Opportunity oportunidade;
    private Comissao comissao = new Comissao();

    public ProcessamentoComissionadosQueueable(Comissao__c comissaoObj, Opportunity oportunidade) {
        this.comissaoObj = comissaoObj;
        this.oportunidade = oportunidade;
    }

    public void execute(QueueableContext context) { 
        try {
            //Gera objeto context de Comissao, e acordo com os parametros de oportunidade
            ComissaoSchema.ComissaoContext comissaoContext = this.comissao.retornarComissaoContext(comissaoObj, oportunidade);

            //Encontra qual fluxo de comissão deve ser executado
            IFluxoComissao fluxoComissao = this.comissao.encontrarFluxoComissao(comissaoContext);

            //Encontra o tipo exato da comissão de acordo com as regra estabelecidas por cada BU
            comissaoContext.tipoComissao = fluxoComissao.definirTipoComissao(comissaoContext);

            //Gera comissionados e realiza rateio de acordo com as regras do fluxo
            List<Comissionado__c> comissionados = fluxoComissao.encontrarComissionados(comissaoContext);
            if(comissionados != null)
                insert comissionados;
            
        } catch (Exception ex) {
            String mensagemErro = ex.getMessage() + ' - ' + ex.getStackTraceString();
            throw new ComissaoException(mensagemErro);
        }
    }
}